from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
SCALING_GATES = REPO_ROOT / "config" / "scaling_gates"


def gate_path(filename: str) -> Path:
    return SCALING_GATES / filename


RESIDENT_EXECUTION_LAUNCH_OVERHEAD_REDUCTION_GATE = gate_path("resident_execution_launch_overhead_reduction_gate.json")
RESIDENT_EXECUTION_LAUNCH_OVERHEAD_REDUCTION_ANALYSIS_GATE = gate_path("resident_execution_launch_overhead_reduction_analysis_gate.json")
RESIDENT_EXECUTION_LAUNCH_OVERHEAD_REDUCTION_ANALYSIS_REVIEW_GATE = gate_path("resident_execution_launch_overhead_reduction_analysis_review_gate.json")
SINGLE_STATE_REPEATED_LAUNCH_ISOLATION_MEASUREMENT_GATE = gate_path("single_state_repeated_launch_isolation_measurement_gate.json")
SINGLE_STATE_REPEATED_LAUNCH_ISOLATION_MEASUREMENT_RESULT_GATE = gate_path("single_state_repeated_launch_isolation_measurement_result_gate.json")
SINGLE_STATE_REPEATED_LAUNCH_ISOLATION_MEASUREMENT_REVIEW_GATE = gate_path("single_state_repeated_launch_isolation_measurement_review_gate.json")
SINGLE_STATE_LAUNCH_ORCHESTRATION_CLEANUP_GATE = gate_path("single_state_launch_orchestration_cleanup_gate.json")
SINGLE_STATE_LAUNCH_ORCHESTRATION_CLEANUP_SURFACE_INSPECTION_GATE = gate_path("single_state_launch_orchestration_cleanup_surface_inspection_gate.json")
REPEAT_MEDIAN_SUMMARY_HELPER_CLEANUP_IMPLEMENTATION_GATE = gate_path("repeat_median_summary_helper_cleanup_implementation_gate.json")
REPEAT_MEDIAN_SUMMARY_HELPER_CLEANUP_REVIEW_GATE = gate_path("repeat_median_summary_helper_cleanup_review_gate.json")
NEXT_GOAL_SELECTION_AFTER_HELPER_CLEANUP_REVIEW_GATE = gate_path("next_goal_selection_after_helper_cleanup_review_gate.json")
PAGED_ATTENTION_KV_CACHE_SCALE_UP_FOLLOWUP_GATE = gate_path("paged_attention_kv_cache_scale_up_followup_gate.json")
PAGED_ATTENTION_KV_CACHE_SCALE_UP_FOLLOWUP_DRY_RUN_GATE = gate_path("paged_attention_kv_cache_scale_up_followup_dry_run_gate.json")
PAGED_ATTENTION_KV_CACHE_SCALE_UP_FOLLOWUP_MEASUREMENT_GATE = gate_path("paged_attention_kv_cache_scale_up_followup_measurement_gate.json")
PAGED_ATTENTION_KV_CACHE_SCALE_UP_FOLLOWUP_MEASUREMENT_REVIEW_GATE = gate_path("paged_attention_kv_cache_scale_up_followup_measurement_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_PAGED_ATTENTION_KV_CACHE_SCALE_UP_FOLLOWUP_GATE = gate_path("public_results_packaging_refresh_after_paged_attention_kv_cache_scale_up_followup_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_PAGED_ATTENTION_KV_CACHE_SCALE_UP_FOLLOWUP_GATE = gate_path("public_benchmark_pack_externalization_completion_after_paged_attention_kv_cache_scale_up_followup_gate.json")
RESIDENT_EXECUTION_OVERHEAD_BREAKDOWN_GATE = gate_path("resident_execution_overhead_breakdown_gate.json")
RESIDENT_EXECUTION_OVERHEAD_BREAKDOWN_ANALYSIS_GATE = gate_path("resident_execution_overhead_breakdown_analysis_gate.json")
RESIDENT_EXECUTION_OVERHEAD_RUNTIME_BOUNDARY_REVIEW_GATE = gate_path("resident_execution_overhead_runtime_boundary_review_gate.json")
PERSISTENT_RESIDENT_STATE_ABI_SHAPE_PHASE_SWEEP_GATE = gate_path("persistent_resident_state_abi_shape_phase_sweep_gate.json")
PERSISTENT_RESIDENT_STATE_ABI_SHAPE_PHASE_SWEEP_WORKFLOW_GATE = gate_path("persistent_resident_state_abi_shape_phase_sweep_workflow_gate.json")
PERSISTENT_RESIDENT_STATE_ABI_SHAPE_PHASE_SWEEP_MEASUREMENT_GATE = gate_path("persistent_resident_state_abi_shape_phase_sweep_measurement_gate.json")
PERSISTENT_RESIDENT_STATE_ABI_SHAPE_PHASE_SWEEP_MEASUREMENT_REVIEW_GATE = gate_path("persistent_resident_state_abi_shape_phase_sweep_measurement_review_gate.json")
PUBLIC_RESULTS_PERSISTENT_RESIDENT_STATE_ABI_SHAPE_PHASE_SWEEP_REFRESH_GATE = gate_path("public_results_packaging_refresh_after_persistent_resident_state_abi_shape_phase_sweep_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_PERSISTENT_RESIDENT_STATE_ABI_SHAPE_PHASE_SWEEP_GATE = gate_path("public_benchmark_pack_externalization_completion_after_persistent_resident_state_abi_shape_phase_sweep_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_PERSISTENT_RESIDENT_STATE_ABI_SHAPE_PHASE_SWEEP_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_persistent_resident_state_abi_shape_phase_sweep_public_pack_refresh_gate.json")
PAGED_ATTENTION_KV_CACHE_SCALE_UP_CONTINUATION_GATE = gate_path("paged_attention_kv_cache_scale_up_continuation_gate.json")
PAGED_ATTENTION_KV_CACHE_SCALE_UP_CONTINUATION_DRY_RUN_GATE = gate_path("paged_attention_kv_cache_scale_up_continuation_dry_run_gate.json")
PAGED_ATTENTION_KV_CACHE_SCALE_UP_CONTINUATION_DRY_RUN_REVIEW_GATE = gate_path("paged_attention_kv_cache_scale_up_continuation_dry_run_review_gate.json")
PAGED_ATTENTION_KV_CACHE_SCALE_UP_CONTINUATION_MEASUREMENT_GATE = gate_path("paged_attention_kv_cache_scale_up_continuation_measurement_gate.json")
PAGED_ATTENTION_KV_CACHE_SCALE_UP_CONTINUATION_MEASUREMENT_REVIEW_GATE = gate_path("paged_attention_kv_cache_scale_up_continuation_measurement_review_gate.json")
ONE_COMMAND_REPRODUCTION_GATE = gate_path("one_command_reproduction_flow_gate.json")
REPEAT_MEDIAN_RESULTS_GATE = gate_path("repeat_median_results_reproduction_gate.json")
RESIDENT_OPTIMIZATION_NEXT_GATE = gate_path("resident_execution_optimization_next_gate.json")
RESIDENT_BATCH_SWEEP_GATE = gate_path("resident_batch_sweep_measurement_gate.json")
RESIDENT_BATCH_SWEEP_REVIEW_GATE = gate_path("resident_batch_sweep_review_gate.json")
RESIDENT_STATE_REUSE_EXPERIMENT_GATE = gate_path("resident_state_reuse_experiment_gate.json")
RESIDENT_STATE_REUSE_MEASUREMENT_GATE = gate_path("resident_state_reuse_measurement_gate.json")
RESIDENT_STATE_REUSE_REVIEW_GATE = gate_path("resident_state_reuse_review_gate.json")
PERSISTENT_RESIDENT_STATE_ABI_PROBE_GATE = gate_path("persistent_resident_state_abi_probe_gate.json")
PERSISTENT_RESIDENT_STATE_ABI_IMPLEMENTATION_GATE = gate_path("persistent_resident_state_abi_probe_implementation_gate.json")
PERSISTENT_RESIDENT_DEVICE_HANDLE_STORAGE_GATE = gate_path("persistent_resident_device_handle_storage_gate.json")
PERSISTENT_RESIDENT_DEVICE_HANDLE_STORAGE_REVIEW_GATE = gate_path("persistent_resident_device_handle_storage_review_gate.json")
PERSISTENT_RESIDENT_STATE_ABI_REPEAT_MEDIAN_GATE = gate_path("persistent_resident_state_abi_repeat_median_measurement_gate.json")
NEXT_GOAL_AFTER_PERSISTENT_RESIDENT_REPEAT_MEDIAN_GATE = gate_path("next_goal_selection_after_persistent_resident_repeat_median_gate.json")
CANDIDATE_TEMPLATE_SELECTION_GATE = gate_path("candidate_template_clean_checkout_selection_gate.json")
NVDLA_CMAC_CORE_MAC_MINIMAL_GATE = gate_path("nvdla_cmac_core_mac_minimal_build_run_compare_gate.json")
NVDLA_CMAC_CORE_MAC_TEMPLATE_SHAPE_EXPANSION_GATE = gate_path("nvdla_cmac_core_mac_template_shape_expansion_gate.json")
NVDLA_SHAPE_EXPANSION_NEXT_WORKSTREAM_REVIEW_GATE = gate_path("nvdla_shape_expansion_next_workstream_review_gate.json")
ITA_DEPENDENCY_CLEAN_CHECKOUT_BOUNDARY_GATE = gate_path("ita_dependency_clean_checkout_boundary_gate.json")
ITA_FIRST_SEED_SELECTION_AFTER_DEPENDENCY_BOUNDARY_GATE = gate_path("ita_first_seed_selection_after_dependency_boundary_gate.json")
PULP_ITA_DOTP_OVERLAY_TEMPLATE_GENERIC_HOST_PROBE_GATE = gate_path("pulp_ita_dotp_overlay_template_generic_host_probe_gate.json")
PULP_ITA_DOTP_FIRST_GENERIC_HOST_PROBE_BUILD_RUN_COMPARE_GATE = gate_path("pulp_ita_dotp_first_generic_host_probe_build_run_compare_gate.json")
PULP_ITA_DOTP_SHAPE_EXPANSION_GATE = gate_path("pulp_ita_dotp_shape_expansion_gate.json")
PULP_ITA_DOTP_SHAPE_EXPANSION_REVIEW_GATE = gate_path("pulp_ita_dotp_shape_expansion_review_gate.json")
PULP_ITA_SOFTMAX_TOP_DEPENDENCY_TEMPLATE_BOUNDARY_GATE = gate_path("pulp_ita_softmax_top_dependency_template_boundary_gate.json")
PULP_ITA_SOFTMAX_TOP_FIRST_GENERIC_HOST_PROBE_BUILD_RUN_COMPARE_GATE = gate_path("pulp_ita_softmax_top_first_generic_host_probe_build_run_compare_gate.json")
PULP_ITA_SOFTMAX_TOP_SHAPE_EXPANSION_GATE = gate_path("pulp_ita_softmax_top_shape_expansion_gate.json")
PULP_ITA_SOFTMAX_TOP_SHAPE_EXPANSION_REVIEW_GATE = gate_path("pulp_ita_softmax_top_shape_expansion_review_gate.json")
PULP_ITA_MHA_DEPENDENCY_TEMPLATE_BOUNDARY_GATE = gate_path("pulp_ita_mha_dependency_template_boundary_gate.json")
PULP_ITA_MHA_FIRST_GENERIC_HOST_PROBE_BUILD_RUN_COMPARE_GATE = gate_path("pulp_ita_mha_first_generic_host_probe_build_run_compare_gate.json")
PULP_ITA_MHA_SHAPE_EXPANSION_GATE = gate_path("pulp_ita_mha_shape_expansion_gate.json")
PULP_ITA_MHA_SHAPE_EXPANSION_REVIEW_GATE = gate_path("pulp_ita_mha_shape_expansion_review_gate.json")


__all__ = [
    name
    for name in globals()
    if not name.startswith("_")
]
