import json
from pathlib import Path

from tests.contract.full_ita_mha_larger_paged_kv_next_resources import *  # noqa: F403
from tests.contract.full_ita_mha_larger_paged_kv_next_runtime_gates import *  # noqa: F403


REPO_ROOT = Path(__file__).resolve().parents[2]
SCALING_GATES = REPO_ROOT / "config" / "scaling_gates"
REPORTS = REPO_ROOT / "reports"
SLICE_LAUNCH_TEMPLATES = REPO_ROOT / "config" / "slice_launch_templates"
ITA_OVERLAY_SRC = REPO_ROOT / "overlays" / "ITA" / "src"
ITA_OVERLAY_TESTS = REPO_ROOT / "overlays" / "ITA" / "tests"
NVDLA_OVERLAY_ROOT = REPO_ROOT / "overlays" / "rtlmeter" / "designs" / "NVDLA"


def gate_path(filename: str) -> Path:
    return SCALING_GATES / filename


def report_path(filename: str) -> Path:
    return REPORTS / filename


def template_path(filename: str) -> Path:
    return SLICE_LAUNCH_TEMPLATES / filename


def ita_src_path(filename: str) -> Path:
    return ITA_OVERLAY_SRC / filename


def ita_test_path(filename: str) -> Path:
    return ITA_OVERLAY_TESTS / filename


def read_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def read_selection() -> object:
    import sys

    tools_dir = REPO_ROOT / "src" / "tools"
    tools_s = str(tools_dir)
    if tools_s not in sys.path:
        sys.path.insert(0, tools_s)
    import selection_state

    return selection_state.load_selection(REPO_ROOT)


def read_combined_docs(*paths: Path) -> str:
    selected_paths = paths or (README, STATUS, ROADMAP, RESULTS)
    return "\n".join(path.read_text(encoding="utf-8") for path in selected_paths)


CURRENT_PRIORITY = "define_verilator_native_option_parser_direct_command_path_fixture_payload_validation_hardening_gate"
CURRENT_PRIORITY_SOURCE_ARTIFACT = (
    "config/scaling_gates/review_verilator_native_option_parser_direct_command_path_fixture_implementation_gate.json"
)


NEXT_GATE = gate_path("neural_network_rtl_full_ita_mha_and_larger_paged_kv_next_gate.json")
LARGE_KV_GATE = gate_path("neural_network_rtl_paged_kv_cache_large_scaleup_gate.json")
LARGE_KV_REVIEW_GATE = gate_path("neural_network_rtl_paged_kv_cache_large_review_gate.json")
FULL_ITA_MHA_AUDIT_GATE = gate_path("neural_network_rtl_full_ita_mha_dependency_audit_gate.json")
FULL_ITA_MHA_BENCHMARK_GATE = gate_path("neural_network_rtl_full_ita_mha_first_hybrid_benchmark_gate.json")
GOAL_REVIEW_GATE = gate_path("neural_network_rtl_full_ita_mha_larger_paged_kv_goal_review_gate.json")
PAGED_ATTENTION_GATE = gate_path("neural_network_rtl_paged_attention_kv_score_harness_gate.json")
COMPLETION_AUDIT = gate_path("full_ita_mha_larger_paged_attention_kv_goal_completion_audit.json")
MODERN_LLM_COMPLETION_AUDIT = gate_path("modern_llm_serving_rtl_hybrid_conditions_goal_completion_audit.json")
PUBLIC_RESULTS_GATE = gate_path("public_results_packaging_gate.json")
PUBLIC_RESULTS_MHA_REFRESH_GATE = gate_path("public_results_packaging_refresh_after_pulp_ita_mha_shape_expansion_gate.json")
PUBLIC_RESULTS_PERSISTENT_REPEAT_MEDIAN_REFRESH_GATE = gate_path("public_results_packaging_refresh_after_persistent_resident_repeat_median_gate.json")
PUBLIC_BENCHMARK_PACK_COMPLETION_AUDIT = gate_path("public_benchmark_pack_goal_completion_audit.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_AUDIT = gate_path("public_benchmark_pack_externalization_readiness_audit.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_GATE = gate_path("public_benchmark_pack_externalization_completion_gate.json")
NEXT_MEASUREMENT_GOAL_SELECTION_GATE = gate_path("next_measurement_goal_selection_after_public_pack_readiness_gate.json")
NEXT_MEASUREMENT_AFTER_PUBLIC_PACK_EXTERNALIZATION_GATE = gate_path("next_measurement_selection_after_public_benchmark_pack_externalization_gate.json")
PAGED_ATTENTION_KV_CACHE_SCALE_UP_MEASUREMENT_GATE = gate_path("paged_attention_kv_cache_scale_up_measurement_gate.json")
PAGED_ATTENTION_KV_CACHE_SCALE_UP_MEASUREMENT_REVIEW_GATE = gate_path("paged_attention_kv_cache_scale_up_measurement_review_gate.json")
PAGED_ATTENTION_KV_CACHE_TIMING_SUMMARY_GATE = gate_path("paged_attention_kv_cache_timing_summary_gate.json")
PAGED_ATTENTION_KV_CACHE_TIMING_SUMMARY_REVIEW_GATE = gate_path("paged_attention_kv_cache_timing_summary_review_gate.json")
PUBLIC_RESULTS_PAGED_ATTENTION_KV_TIMING_REFRESH_GATE = gate_path("public_results_packaging_refresh_after_paged_attention_kv_cache_timing_summary_gate.json")
PUBLIC_PACK_COMPLETION_AFTER_PAGED_ATTENTION_KV_TIMING_REFRESH_GATE = gate_path("public_benchmark_pack_externalization_completion_after_paged_attention_kv_cache_timing_summary_gate.json")
NEXT_MEASUREMENT_AFTER_PAGED_ATTENTION_KV_TIMING_REFRESH_GATE = gate_path("next_measurement_selection_after_paged_attention_kv_cache_timing_refresh_gate.json")
PAGED_ATTENTION_KV_CACHE_REPEAT_MEDIAN_TIMING_GATE = gate_path("paged_attention_kv_cache_repeat_median_timing_gate.json")
PAGED_ATTENTION_KV_CACHE_REPEAT_MEDIAN_WORKFLOW_GATE = gate_path("paged_attention_kv_cache_repeat_median_workflow_gate.json")
PAGED_ATTENTION_KV_CACHE_REPEAT_MEDIAN_MEASUREMENT_GATE = gate_path("paged_attention_kv_cache_repeat_median_measurement_gate.json")
PAGED_ATTENTION_KV_CACHE_REPEAT_MEDIAN_REVIEW_GATE = gate_path("paged_attention_kv_cache_repeat_median_review_gate.json")
PUBLIC_RESULTS_PAGED_ATTENTION_KV_REPEAT_MEDIAN_REFRESH_GATE = gate_path("public_results_packaging_refresh_after_paged_attention_kv_cache_repeat_median_gate.json")
PUBLIC_PACK_COMPLETION_AFTER_PAGED_ATTENTION_KV_REPEAT_MEDIAN_REFRESH_GATE = gate_path("public_benchmark_pack_externalization_completion_after_paged_attention_kv_cache_repeat_median_gate.json")
NEXT_MEASUREMENT_AFTER_PAGED_ATTENTION_KV_REPEAT_MEDIAN_REFRESH_GATE = gate_path("next_measurement_selection_after_paged_attention_kv_cache_repeat_median_refresh_gate.json")
CONFIG_GENERATION_VALIDATION_BREADTH_GATE = gate_path("config_generation_validation_breadth_gate.json")
CONFIG_GENERATION_VALIDATION_BREADTH_DRY_RUN_GATE = gate_path("config_generation_validation_breadth_dry_run_gate.json")
CONFIG_GENERATION_VALIDATION_BREADTH_DRY_RUN_REVIEW_GATE = gate_path("config_generation_validation_breadth_dry_run_review_gate.json")
CONFIG_GENERATION_VALIDATION_BREADTH_EXECUTION_GATE = gate_path("config_generation_validation_breadth_execution_gate.json")
CONFIG_GENERATION_VALIDATION_BREADTH_EXECUTION_RESULT_GATE = gate_path("config_generation_validation_breadth_execution_result_gate.json")
CONFIG_GENERATION_VALIDATION_BREADTH_EXECUTION_REVIEW_GATE = gate_path("config_generation_validation_breadth_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_CONFIG_GENERATION_VALIDATION_BREADTH_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_config_generation_validation_breadth_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_CONFIG_GENERATION_VALIDATION_BREADTH_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_config_generation_validation_breadth_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_CONFIG_GENERATION_VALIDATION_BREADTH_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_config_generation_validation_breadth_public_pack_refresh_gate.json")
CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_GATE = gate_path("config_generation_validation_shape_breadth_gate.json")
CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_DRY_RUN_GATE = gate_path("config_generation_validation_shape_breadth_dry_run_gate.json")
CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_DRY_RUN_REVIEW_GATE = gate_path("config_generation_validation_shape_breadth_dry_run_review_gate.json")
CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_EXECUTION_GATE = gate_path("config_generation_validation_shape_breadth_execution_gate.json")
CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_EXECUTION_RESULT_GATE = gate_path("config_generation_validation_shape_breadth_execution_result_gate.json")
CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_EXECUTION_REVIEW_GATE = gate_path("config_generation_validation_shape_breadth_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_config_generation_validation_shape_breadth_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_config_generation_validation_shape_breadth_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_config_generation_validation_shape_breadth_public_pack_refresh_gate.json")
CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_GATE = gate_path("config_generation_validation_additional_targets_gate.json")
CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_DRY_RUN_GATE = gate_path("config_generation_validation_additional_targets_dry_run_gate.json")
CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_DRY_RUN_REVIEW_GATE = gate_path("config_generation_validation_additional_targets_dry_run_review_gate.json")
CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_EXECUTION_GATE = gate_path("config_generation_validation_additional_targets_execution_gate.json")
CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_EXECUTION_RESULT_GATE = gate_path("config_generation_validation_additional_targets_execution_result_gate.json")
CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_EXECUTION_REVIEW_GATE = gate_path("config_generation_validation_additional_targets_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_config_generation_validation_additional_targets_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_config_generation_validation_additional_targets_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_config_generation_validation_additional_targets_public_pack_refresh_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_GATE = gate_path("tlul_template_schema_normalization_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_IMPLEMENTATION_GATE = gate_path("tlul_template_schema_normalization_implementation_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_IMPLEMENTATION_REVIEW_GATE = gate_path("tlul_template_schema_normalization_implementation_review_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EXECUTION_GATE = gate_path("tlul_template_schema_normalization_execution_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EXECUTION_RESULT_GATE = gate_path("tlul_template_schema_normalization_execution_result_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EXECUTION_REVIEW_GATE = gate_path("tlul_template_schema_normalization_execution_review_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_GATE = gate_path("tlul_template_schema_normalization_breadth_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_DRY_RUN_GATE = gate_path("tlul_template_schema_normalization_breadth_dry_run_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_DRY_RUN_REVIEW_GATE = gate_path("tlul_template_schema_normalization_breadth_dry_run_review_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_EXECUTION_GATE = gate_path("tlul_template_schema_normalization_breadth_execution_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_EXECUTION_RESULT_GATE = gate_path("tlul_template_schema_normalization_breadth_execution_result_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_EXECUTION_REVIEW_GATE = gate_path("tlul_template_schema_normalization_breadth_execution_review_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_PUBLIC_PACK_REFRESH_GATE = gate_path("tlul_template_schema_normalization_breadth_public_pack_refresh_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_GATE = gate_path("public_benchmark_pack_externalization_completion_after_tlul_template_schema_normalization_breadth_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_tlul_template_schema_normalization_breadth_public_pack_refresh_gate.json")
TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_GATE = gate_path("tlul_legacy_clock_reset_metadata_matrix_gate.json")
TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_DRY_RUN_GATE = gate_path("tlul_legacy_clock_reset_metadata_matrix_dry_run_gate.json")
TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_DRY_RUN_REVIEW_GATE = gate_path("tlul_legacy_clock_reset_metadata_matrix_dry_run_review_gate.json")
TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_EXECUTION_GATE = gate_path("tlul_legacy_clock_reset_metadata_matrix_execution_gate.json")
TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_EXECUTION_RESULT_GATE = gate_path("tlul_legacy_clock_reset_metadata_matrix_execution_result_gate.json")
TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_EXECUTION_REVIEW_GATE = gate_path("tlul_legacy_clock_reset_metadata_matrix_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_tlul_legacy_clock_reset_metadata_matrix_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_tlul_legacy_clock_reset_metadata_matrix_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_tlul_legacy_clock_reset_metadata_matrix_public_pack_refresh_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_GATE = gate_path("tlul_template_schema_normalization_more_breadth_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_DRY_RUN_GATE = gate_path("tlul_template_schema_normalization_more_breadth_dry_run_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_DRY_RUN_REVIEW_GATE = gate_path("tlul_template_schema_normalization_more_breadth_dry_run_review_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_EXECUTION_GATE = gate_path("tlul_template_schema_normalization_more_breadth_execution_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_EXECUTION_RESULT_GATE = gate_path("tlul_template_schema_normalization_more_breadth_execution_result_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_EXECUTION_REVIEW_GATE = gate_path("tlul_template_schema_normalization_more_breadth_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_tlul_template_schema_normalization_more_breadth_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_tlul_template_schema_normalization_more_breadth_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_tlul_template_schema_normalization_more_breadth_public_pack_refresh_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_GATE = gate_path("tlul_template_schema_normalization_even_more_breadth_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_DRY_RUN_GATE = gate_path("tlul_template_schema_normalization_even_more_breadth_dry_run_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_DRY_RUN_REVIEW_GATE = gate_path("tlul_template_schema_normalization_even_more_breadth_dry_run_review_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_EXECUTION_GATE = gate_path("tlul_template_schema_normalization_even_more_breadth_execution_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_EXECUTION_RESULT_GATE = gate_path("tlul_template_schema_normalization_even_more_breadth_execution_result_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_EXECUTION_REVIEW_GATE = gate_path("tlul_template_schema_normalization_even_more_breadth_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_tlul_template_schema_normalization_even_more_breadth_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_tlul_template_schema_normalization_even_more_breadth_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_tlul_template_schema_normalization_even_more_breadth_public_pack_refresh_gate.json")
CONFIG_GENERATION_VALIDATION_FOLLOWUP_GATE = gate_path("config_generation_validation_followup_gate.json")
CONFIG_GENERATION_VALIDATION_FOLLOWUP_DRY_RUN_GATE = gate_path("config_generation_validation_followup_dry_run_gate.json")
CONFIG_GENERATION_VALIDATION_FOLLOWUP_DRY_RUN_REVIEW_GATE = gate_path("config_generation_validation_followup_dry_run_review_gate.json")
CONFIG_GENERATION_VALIDATION_FOLLOWUP_EXECUTION_GATE = gate_path("config_generation_validation_followup_execution_gate.json")
CONFIG_GENERATION_VALIDATION_FOLLOWUP_EXECUTION_RESULT_GATE = gate_path("config_generation_validation_followup_execution_result_gate.json")
CONFIG_GENERATION_VALIDATION_FOLLOWUP_EXECUTION_REVIEW_GATE = gate_path("config_generation_validation_followup_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_CONFIG_GENERATION_VALIDATION_FOLLOWUP_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_config_generation_validation_followup_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_CONFIG_GENERATION_VALIDATION_FOLLOWUP_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_config_generation_validation_followup_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_CONFIG_GENERATION_VALIDATION_FOLLOWUP_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_config_generation_validation_followup_public_pack_refresh_gate.json")
TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_REVIEW_GATE = gate_path("tlul_template_schema_metadata_invariant_review_gate.json")
TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_REVIEW_DRY_RUN_GATE = gate_path("tlul_template_schema_metadata_invariant_review_dry_run_gate.json")
TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_REVIEW_DRY_RUN_REVIEW_GATE = gate_path("tlul_template_schema_metadata_invariant_review_dry_run_review_gate.json")
TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_EXECUTION_GATE = gate_path("tlul_template_schema_metadata_invariant_execution_gate.json")
TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_EXECUTION_RESULT_GATE = gate_path("tlul_template_schema_metadata_invariant_execution_result_gate.json")
TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_EXECUTION_REVIEW_GATE = gate_path("tlul_template_schema_metadata_invariant_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_tlul_template_schema_metadata_invariant_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_tlul_template_schema_metadata_invariant_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_tlul_template_schema_metadata_invariant_public_pack_refresh_gate.json")
VERILATOR_LIKE_HYBRID_ENTRYPOINT_OPTION_SURFACE_GATE = gate_path("verilator_like_hybrid_entrypoint_option_surface_gate.json")
VERILATOR_LIKE_HYBRID_ENTRYPOINT_OPTION_SURFACE_DRY_RUN_GATE = gate_path("verilator_like_hybrid_entrypoint_option_surface_dry_run_gate.json")
VERILATOR_LIKE_HYBRID_ENTRYPOINT_OPTION_SURFACE_DRY_RUN_REVIEW_GATE = gate_path("verilator_like_hybrid_entrypoint_option_surface_dry_run_review_gate.json")
VERILATOR_LIKE_HYBRID_ENTRYPOINT_OPTION_SURFACE_EXECUTION_GATE = gate_path("verilator_like_hybrid_entrypoint_option_surface_execution_gate.json")
VERILATOR_LIKE_HYBRID_ENTRYPOINT_OPTION_SURFACE_EXECUTION_RESULT_GATE = gate_path("verilator_like_hybrid_entrypoint_option_surface_execution_result_gate.json")
VERILATOR_LIKE_HYBRID_ENTRYPOINT_OPTION_SURFACE_EXECUTION_REVIEW_GATE = gate_path("verilator_like_hybrid_entrypoint_option_surface_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_VERILATOR_LIKE_HYBRID_ENTRYPOINT_OPTION_SURFACE_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_verilator_like_hybrid_entrypoint_option_surface_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_VERILATOR_LIKE_HYBRID_ENTRYPOINT_OPTION_SURFACE_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_verilator_like_hybrid_entrypoint_option_surface_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_VERILATOR_LIKE_HYBRID_ENTRYPOINT_OPTION_SURFACE_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_verilator_like_hybrid_entrypoint_option_surface_public_pack_refresh_gate.json")
FILELIST_TO_VERILATOR_LIKE_HYBRID_PLAN_BOUNDARY_GATE = gate_path("filelist_to_verilator_like_hybrid_plan_boundary_gate.json")
FILELIST_TO_VERILATOR_LIKE_HYBRID_PLAN_BOUNDARY_DRY_RUN_GATE = gate_path("filelist_to_verilator_like_hybrid_plan_boundary_dry_run_gate.json")
FILELIST_TO_VERILATOR_LIKE_HYBRID_PLAN_BOUNDARY_DRY_RUN_REVIEW_GATE = gate_path("filelist_to_verilator_like_hybrid_plan_boundary_dry_run_review_gate.json")
FILELIST_TO_VERILATOR_LIKE_HYBRID_PLAN_BOUNDARY_MATERIALIZATION_GATE = gate_path("filelist_to_verilator_like_hybrid_plan_boundary_materialization_gate.json")
FILELIST_TO_VERILATOR_LIKE_HYBRID_PLAN_BOUNDARY_MATERIALIZATION_RESULT_GATE = gate_path("filelist_to_verilator_like_hybrid_plan_boundary_materialization_result_gate.json")
FILELIST_TO_VERILATOR_LIKE_HYBRID_PLAN_BOUNDARY_MATERIALIZATION_REVIEW_GATE = gate_path("filelist_to_verilator_like_hybrid_plan_boundary_materialization_review_gate.json")
FILELIST_PAGED_ATTENTION_KV_SCORE_FIRST_HYBRID_BENCHMARK_GATE = gate_path("filelist_paged_attention_kv_score_first_hybrid_benchmark_gate.json")
FILELIST_MATERIALIZED_TEMPLATE_DRY_RUN_GATE = gate_path("filelist_materialized_template_dry_run_gate.json")
FILELIST_MATERIALIZED_TEMPLATE_DRY_RUN_RESULT_GATE = gate_path("filelist_materialized_template_dry_run_result_gate.json")
FILELIST_MATERIALIZED_TEMPLATE_DRY_RUN_REVIEW_GATE = gate_path("filelist_materialized_template_dry_run_review_gate.json")
FILELIST_MATERIALIZED_TEMPLATE_EXECUTION_GATE = gate_path("filelist_materialized_template_execution_gate.json")
FILELIST_MATERIALIZED_TEMPLATE_EXECUTION_RESULT_GATE = gate_path("filelist_materialized_template_execution_result_gate.json")
FILELIST_MATERIALIZED_TEMPLATE_EXECUTION_REVIEW_GATE = gate_path("filelist_materialized_template_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_MATERIALIZED_TEMPLATE_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_filelist_materialized_template_execution_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_MATERIALIZED_TEMPLATE_EXECUTION_RESULT_GATE = gate_path("public_results_packaging_refresh_after_filelist_materialized_template_execution_result_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_MATERIALIZED_TEMPLATE_EXECUTION_REVIEW_GATE = gate_path("public_results_packaging_refresh_after_filelist_materialized_template_execution_review_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_FILELIST_MATERIALIZED_TEMPLATE_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_filelist_materialized_template_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_FILELIST_MATERIALIZED_TEMPLATE_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_filelist_materialized_template_public_pack_refresh_gate.json")
FILELIST_SOURCE_CLOSURE_DEPENDENCY_POLICY_GATE = gate_path("filelist_source_closure_dependency_policy_gate.json")
FILELIST_SOURCE_CLOSURE_DEPENDENCY_POLICY_DRY_RUN_RESULT_GATE = gate_path(
    "filelist_source_closure_dependency_policy_dry_run_result_gate.json"
)
FILELIST_SOURCE_CLOSURE_DEPENDENCY_POLICY_DRY_RUN_REVIEW_GATE = gate_path(
    "filelist_source_closure_dependency_policy_dry_run_review_gate.json"
)
FILELIST_SOURCE_CLOSURE_NON_DRY_RUN_REFUSAL_GATE = gate_path(
    "filelist_source_closure_non_dry_run_refusal_gate.json"
)
FILELIST_SOURCE_CLOSURE_NON_DRY_RUN_REFUSAL_RESULT_GATE = gate_path(
    "filelist_source_closure_non_dry_run_refusal_result_gate.json"
)
FILELIST_SOURCE_CLOSURE_NON_DRY_RUN_REFUSAL_REVIEW_GATE = gate_path(
    "filelist_source_closure_non_dry_run_refusal_review_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SOURCE_CLOSURE_REFUSAL_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_source_closure_refusal_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SOURCE_CLOSURE_REFUSAL_RESULT_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_source_closure_refusal_result_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SOURCE_CLOSURE_REFUSAL_REVIEW_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_source_closure_refusal_review_gate.json"
)
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_FILELIST_SOURCE_CLOSURE_REFUSAL_GATE = gate_path(
    "public_benchmark_pack_externalization_completion_after_filelist_source_closure_refusal_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_FILELIST_SOURCE_CLOSURE_REFUSAL_PUBLIC_PACK_REFRESH_GATE = gate_path(
    "next_measurement_selection_after_filelist_source_closure_refusal_public_pack_refresh_gate.json"
)
FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_GATE = gate_path(
    "filelist_known_template_source_closure_copy_gate.json"
)
FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_DRY_RUN_RESULT_GATE = gate_path(
    "filelist_known_template_source_closure_copy_dry_run_result_gate.json"
)
FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_DRY_RUN_REVIEW_GATE = gate_path(
    "filelist_known_template_source_closure_copy_dry_run_review_gate.json"
)
FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_MATERIALIZATION_GATE = gate_path(
    "filelist_known_template_source_closure_copy_materialization_gate.json"
)
FILELIST_KNOWN_TEMPLATE_PAGED_ATTENTION_KV_SCORE_FIRST_HYBRID_BENCHMARK_GATE = gate_path(
    "filelist_known_template_paged_attention_kv_score_first_hybrid_benchmark_gate.json"
)
FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_MATERIALIZATION_RESULT_GATE = gate_path(
    "filelist_known_template_source_closure_copy_materialization_result_gate.json"
)
FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_MATERIALIZATION_REVIEW_GATE = gate_path(
    "filelist_known_template_source_closure_copy_materialization_review_gate.json"
)
FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_MATERIALIZED_TEMPLATE_DRY_RUN_GATE = gate_path(
    "filelist_known_template_source_closure_copy_materialized_template_dry_run_gate.json"
)
FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_MATERIALIZED_TEMPLATE_DRY_RUN_RESULT_GATE = gate_path(
    "filelist_known_template_source_closure_copy_materialized_template_dry_run_result_gate.json"
)
FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_MATERIALIZED_TEMPLATE_DRY_RUN_REVIEW_GATE = gate_path(
    "filelist_known_template_source_closure_copy_materialized_template_dry_run_review_gate.json"
)
FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_MATERIALIZED_TEMPLATE_EXECUTION_GATE = gate_path(
    "filelist_known_template_source_closure_copy_materialized_template_execution_gate.json"
)
FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_MATERIALIZED_TEMPLATE_EXECUTION_RESULT_GATE = gate_path(
    "filelist_known_template_source_closure_copy_materialized_template_execution_result_gate.json"
)
FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_MATERIALIZED_TEMPLATE_EXECUTION_REVIEW_GATE = gate_path(
    "filelist_known_template_source_closure_copy_materialized_template_execution_review_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_EXECUTION_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_known_template_source_closure_copy_execution_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_EXECUTION_RESULT_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_known_template_source_closure_copy_execution_result_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_EXECUTION_REVIEW_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_known_template_source_closure_copy_execution_review_gate.json"
)
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_EXECUTION_GATE = gate_path(
    "public_benchmark_pack_externalization_completion_after_filelist_known_template_source_closure_copy_execution_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_FILELIST_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_EXECUTION_PUBLIC_PACK_REFRESH_GATE = gate_path(
    "next_measurement_selection_after_filelist_known_template_source_closure_copy_execution_public_pack_refresh_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_REFERENCE_INVENTORY_GATE = gate_path(
    "known_template_source_closure_reference_inventory_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_REFERENCE_INVENTORY_RESULT_GATE = gate_path(
    "known_template_source_closure_reference_inventory_result_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_REFERENCE_INVENTORY_REVIEW_GATE = gate_path(
    "known_template_source_closure_reference_inventory_review_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_KNOWN_TEMPLATE_SOURCE_CLOSURE_REFERENCE_INVENTORY_GATE = gate_path(
    "next_measurement_selection_after_known_template_source_closure_reference_inventory_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_INDEPENDENT_REFERENCE_PROMOTION_GATE = gate_path(
    "known_template_source_closure_independent_reference_promotion_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_INDEPENDENT_REFERENCE_PROMOTION_RESULT_GATE = gate_path(
    "known_template_source_closure_independent_reference_promotion_result_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_INDEPENDENT_REFERENCE_PROMOTION_REVIEW_GATE = gate_path(
    "known_template_source_closure_independent_reference_promotion_review_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_KNOWN_TEMPLATE_SOURCE_CLOSURE_INDEPENDENT_REFERENCE_PROMOTION_REVIEW_GATE = gate_path(
    "next_measurement_selection_after_known_template_source_closure_independent_reference_promotion_review_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_VALIDATION_GATE = gate_path(
    "known_template_source_closure_copy_breadth_validation_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_VALIDATION_DRY_RUN_RESULT_GATE = gate_path(
    "known_template_source_closure_copy_breadth_validation_dry_run_result_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_VALIDATION_DRY_RUN_REVIEW_GATE = gate_path(
    "known_template_source_closure_copy_breadth_validation_dry_run_review_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_VALIDATION_DRY_RUN_REVIEW_GATE = gate_path(
    "next_measurement_selection_after_known_template_source_closure_copy_breadth_validation_dry_run_review_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_MATERIALIZATION_GATE = gate_path(
    "known_template_source_closure_copy_breadth_materialization_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_MATERIALIZATION_RESULT_GATE = gate_path(
    "known_template_source_closure_copy_breadth_materialization_result_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_MATERIALIZATION_REVIEW_GATE = gate_path(
    "known_template_source_closure_copy_breadth_materialization_review_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_MATERIALIZATION_REVIEW_GATE = gate_path(
    "next_measurement_selection_after_known_template_source_closure_copy_breadth_materialization_review_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_MATERIALIZED_TEMPLATE_DRY_RUN_GATE = gate_path(
    "known_template_source_closure_copy_breadth_materialized_template_dry_run_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_MATERIALIZED_TEMPLATE_DRY_RUN_RESULT_GATE = gate_path(
    "known_template_source_closure_copy_breadth_materialized_template_dry_run_result_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_MATERIALIZED_TEMPLATE_DRY_RUN_REVIEW_GATE = gate_path(
    "known_template_source_closure_copy_breadth_materialized_template_dry_run_review_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_MATERIALIZED_TEMPLATE_DRY_RUN_REVIEW_GATE = gate_path(
    "next_measurement_selection_after_known_template_source_closure_copy_breadth_materialized_template_dry_run_review_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_MATERIALIZED_TEMPLATE_EXECUTION_GATE = gate_path(
    "known_template_source_closure_copy_breadth_materialized_template_execution_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_MATERIALIZED_TEMPLATE_EXECUTION_RESULT_GATE = gate_path(
    "known_template_source_closure_copy_breadth_materialized_template_execution_result_gate.json"
)
KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_MATERIALIZED_TEMPLATE_EXECUTION_REVIEW_GATE = gate_path(
    "known_template_source_closure_copy_breadth_materialized_template_execution_review_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_EXECUTION_REVIEW_GATE = gate_path(
    "next_measurement_selection_after_known_template_source_closure_copy_breadth_execution_review_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_EXECUTION_GATE = gate_path(
    "public_results_packaging_refresh_after_known_template_source_closure_copy_breadth_execution_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_EXECUTION_RESULT_GATE = gate_path(
    "public_results_packaging_refresh_after_known_template_source_closure_copy_breadth_execution_result_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_EXECUTION_REVIEW_GATE = gate_path(
    "public_results_packaging_refresh_after_known_template_source_closure_copy_breadth_execution_review_gate.json"
)
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_EXECUTION_GATE = gate_path(
    "public_benchmark_pack_externalization_completion_after_known_template_source_closure_copy_breadth_execution_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_KNOWN_TEMPLATE_SOURCE_CLOSURE_COPY_BREADTH_EXECUTION_PUBLIC_PACK_REFRESH_GATE = gate_path(
    "next_measurement_selection_after_known_template_source_closure_copy_breadth_execution_public_pack_refresh_gate.json"
)
VERILATOR_COMPATIBLE_GPU_HYBRID_MINIMAL_BENCH_SUITE_GATE = gate_path(
    "verilator_compatible_gpu_hybrid_minimal_bench_suite_gate.json"
)
VERILATOR_COMPATIBLE_GPU_HYBRID_MINIMAL_BENCH_SUITE_RESULT_GATE = gate_path(
    "verilator_compatible_gpu_hybrid_minimal_bench_suite_result_gate.json"
)
VERILATOR_COMPATIBLE_GPU_HYBRID_MINIMAL_BENCH_SUITE_RUN_RESULT_GATE = gate_path(
    "verilator_compatible_gpu_hybrid_minimal_bench_suite_run_result_gate.json"
)
VERILATOR_COMPATIBLE_GPU_HYBRID_MINIMAL_BENCH_SUITE_RUN_REVIEW_GATE = gate_path(
    "verilator_compatible_gpu_hybrid_minimal_bench_suite_run_review_gate.json"
)
VERILATOR_COMPATIBLE_GPU_HYBRID_MINIMAL_BENCH_SUITE_COMPLETION_AUDIT = gate_path(
    "verilator_compatible_gpu_hybrid_minimal_bench_suite_completion_audit.json"
)
NEXT_MEASURED_BENCHMARK_SELECTION_AFTER_VERILATOR_COMPATIBLE_GPU_HYBRID_MINIMAL_BENCH_SUITE_COMPLETION_GATE = gate_path(
    "next_measured_benchmark_selection_after_verilator_compatible_gpu_hybrid_minimal_bench_suite_completion_gate.json"
)
DEFINE_PERSISTENT_RESIDENT_DECODE_LIKE_FOLLOWUP_MEASUREMENT_GATE = gate_path(
    "define_persistent_resident_decode_like_followup_measurement_gate.json"
)
PERSISTENT_RESIDENT_DECODE_LIKE_FOLLOWUP_MEASUREMENT_RESULT_GATE = gate_path(
    "persistent_resident_decode_like_followup_measurement_result_gate.json"
)
PERSISTENT_RESIDENT_DECODE_LIKE_FOLLOWUP_MEASUREMENT_REVIEW_GATE = gate_path(
    "persistent_resident_decode_like_followup_measurement_review_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_PERSISTENT_RESIDENT_DECODE_LIKE_FOLLOWUP_MEASUREMENT_GATE = gate_path(
    "public_results_packaging_refresh_after_persistent_resident_decode_like_followup_measurement_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_PERSISTENT_RESIDENT_DECODE_LIKE_FOLLOWUP_MEASUREMENT_RESULT_GATE = gate_path(
    "public_results_packaging_refresh_after_persistent_resident_decode_like_followup_measurement_result_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_PERSISTENT_RESIDENT_DECODE_LIKE_FOLLOWUP_MEASUREMENT_REVIEW_GATE = gate_path(
    "public_results_packaging_refresh_after_persistent_resident_decode_like_followup_measurement_review_gate.json"
)
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_PERSISTENT_RESIDENT_DECODE_LIKE_FOLLOWUP_MEASUREMENT_GATE = gate_path(
    "public_benchmark_pack_externalization_completion_after_persistent_resident_decode_like_followup_measurement_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_PERSISTENT_RESIDENT_DECODE_LIKE_FOLLOWUP_PUBLIC_PACK_REFRESH_GATE = gate_path(
    "next_measurement_selection_after_persistent_resident_decode_like_followup_public_pack_refresh_gate.json"
)
DEFINE_FILELIST_SHAPE_BREADTH_TIMING_MEASUREMENT_GATE = gate_path(
    "define_filelist_shape_breadth_timing_measurement_gate.json"
)
FILELIST_SHAPE_BREADTH_TIMING_MEASUREMENT_RESULT_GATE = gate_path(
    "filelist_shape_breadth_timing_measurement_result_gate.json"
)
FILELIST_SHAPE_BREADTH_TIMING_MEASUREMENT_REVIEW_GATE = gate_path(
    "filelist_shape_breadth_timing_measurement_review_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_TIMING_MEASUREMENT_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_timing_measurement_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_TIMING_MEASUREMENT_RESULT_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_timing_measurement_result_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_TIMING_MEASUREMENT_REVIEW_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_timing_measurement_review_gate.json"
)
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_FILELIST_SHAPE_BREADTH_TIMING_MEASUREMENT_GATE = gate_path(
    "public_benchmark_pack_externalization_completion_after_filelist_shape_breadth_timing_measurement_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_FILELIST_SHAPE_BREADTH_TIMING_MEASUREMENT_PUBLIC_PACK_REFRESH_GATE = gate_path(
    "next_measurement_selection_after_filelist_shape_breadth_timing_measurement_public_pack_refresh_gate.json"
)
DEFINE_FILELIST_SHAPE_BREADTH_REPEAT_MEDIAN_TIMING_GATE = gate_path(
    "define_filelist_shape_breadth_repeat_median_timing_gate.json"
)
FILELIST_SHAPE_BREADTH_REPEAT_MEDIAN_WORKFLOW_GATE = gate_path(
    "filelist_shape_breadth_repeat_median_workflow_gate.json"
)
FILELIST_SHAPE_BREADTH_REPEAT_MEDIAN_MEASUREMENT_GATE = gate_path(
    "filelist_shape_breadth_repeat_median_measurement_gate.json"
)
FILELIST_SHAPE_BREADTH_REPEAT_MEDIAN_REVIEW_GATE = gate_path(
    "filelist_shape_breadth_repeat_median_review_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_REPEAT_MEDIAN_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_repeat_median_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_REPEAT_MEDIAN_RESULT_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_repeat_median_result_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_REPEAT_MEDIAN_REVIEW_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_repeat_median_review_gate.json"
)
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_FILELIST_SHAPE_BREADTH_REPEAT_MEDIAN_GATE = gate_path(
    "public_benchmark_pack_externalization_completion_after_filelist_shape_breadth_repeat_median_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_FILELIST_SHAPE_BREADTH_REPEAT_MEDIAN_PUBLIC_PACK_REFRESH_GATE = gate_path(
    "next_measurement_selection_after_filelist_shape_breadth_repeat_median_public_pack_refresh_gate.json"
)
DEFINE_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_GATE = gate_path(
    "define_filelist_shape_breadth_gpu_allocation_policy_gate.json"
)
FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_DRY_RUN_RESULT_GATE = gate_path(
    "filelist_shape_breadth_gpu_allocation_policy_dry_run_result_gate.json"
)
FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_DRY_RUN_REVIEW_GATE = gate_path(
    "filelist_shape_breadth_gpu_allocation_policy_dry_run_review_gate.json"
)
DEFINE_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_EXECUTION_GATE = gate_path(
    "define_filelist_shape_breadth_gpu_allocation_policy_execution_gate.json"
)
FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_EXECUTION_DRY_RUN_RESULT_GATE = gate_path(
    "filelist_shape_breadth_gpu_allocation_policy_execution_dry_run_result_gate.json"
)
FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_EXECUTION_DRY_RUN_REVIEW_GATE = gate_path(
    "filelist_shape_breadth_gpu_allocation_policy_execution_dry_run_review_gate.json"
)
DEFINE_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_NON_DRY_RUN_EXECUTION_GATE = gate_path(
    "define_filelist_shape_breadth_gpu_allocation_policy_non_dry_run_execution_gate.json"
)
FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_NON_DRY_RUN_EXECUTION_RESULT_GATE = gate_path(
    "filelist_shape_breadth_gpu_allocation_policy_non_dry_run_execution_result_gate.json"
)
FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_NON_DRY_RUN_EXECUTION_REVIEW_GATE = gate_path(
    "filelist_shape_breadth_gpu_allocation_policy_non_dry_run_execution_review_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_NON_DRY_RUN_EXECUTION_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_gpu_allocation_policy_non_dry_run_execution_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_NON_DRY_RUN_EXECUTION_RESULT_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_gpu_allocation_policy_non_dry_run_execution_result_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_NON_DRY_RUN_EXECUTION_REVIEW_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_gpu_allocation_policy_non_dry_run_execution_review_gate.json"
)
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_NON_DRY_RUN_EXECUTION_GATE = gate_path(
    "public_benchmark_pack_externalization_completion_after_filelist_shape_breadth_gpu_allocation_policy_non_dry_run_execution_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_NON_DRY_RUN_EXECUTION_PUBLIC_PACK_REFRESH_GATE = gate_path(
    "next_measurement_selection_after_filelist_shape_breadth_gpu_allocation_policy_non_dry_run_execution_public_pack_refresh_gate.json"
)
DEFINE_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_GATE = gate_path(
    "define_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_gate.json"
)
FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_DRY_RUN_RESULT_GATE = gate_path(
    "filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_dry_run_result_gate.json"
)
FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_DRY_RUN_REVIEW_GATE = gate_path(
    "filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_dry_run_review_gate.json"
)
DEFINE_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_NON_DRY_RUN_EXECUTION_GATE = gate_path(
    "define_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_non_dry_run_execution_gate.json"
)
FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_NON_DRY_RUN_EXECUTION_RESULT_GATE = gate_path(
    "filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_non_dry_run_execution_result_gate.json"
)
FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_NON_DRY_RUN_EXECUTION_REVIEW_GATE = gate_path(
    "filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_non_dry_run_execution_review_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_NON_DRY_RUN_EXECUTION_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_non_dry_run_execution_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_NON_DRY_RUN_EXECUTION_RESULT_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_non_dry_run_execution_result_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_NON_DRY_RUN_EXECUTION_REVIEW_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_non_dry_run_execution_review_gate.json"
)
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_NON_DRY_RUN_EXECUTION_GATE = gate_path(
    "public_benchmark_pack_externalization_completion_after_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_non_dry_run_execution_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_NON_DRY_RUN_EXECUTION_PUBLIC_PACK_REFRESH_GATE = gate_path(
    "next_measurement_selection_after_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_non_dry_run_execution_public_pack_refresh_gate.json"
)
DEFINE_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_TIMING_MEASUREMENT_GATE = gate_path(
    "define_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_timing_measurement_gate.json"
)
FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_TIMING_MEASUREMENT_RESULT_GATE = gate_path(
    "filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_timing_measurement_result_gate.json"
)
FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_TIMING_MEASUREMENT_REVIEW_GATE = gate_path(
    "filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_timing_measurement_review_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_TIMING_MEASUREMENT_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_timing_measurement_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_TIMING_MEASUREMENT_RESULT_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_timing_measurement_result_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_TIMING_MEASUREMENT_REVIEW_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_timing_measurement_review_gate.json"
)
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_TIMING_MEASUREMENT_GATE = gate_path(
    "public_benchmark_pack_externalization_completion_after_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_timing_measurement_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_TIMING_MEASUREMENT_PUBLIC_PACK_REFRESH_GATE = gate_path(
    "next_measurement_selection_after_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_timing_measurement_public_pack_refresh_gate.json"
)
DEFINE_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_REPEAT_MEDIAN_TIMING_GATE = gate_path(
    "define_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_repeat_median_timing_gate.json"
)
FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_REPEAT_MEDIAN_WORKFLOW_GATE = gate_path(
    "filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_repeat_median_workflow_gate.json"
)
FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_REPEAT_MEDIAN_MEASUREMENT_GATE = gate_path(
    "filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_repeat_median_measurement_gate.json"
)
FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_REPEAT_MEDIAN_REVIEW_GATE = gate_path(
    "filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_repeat_median_review_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_REPEAT_MEDIAN_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_repeat_median_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_REPEAT_MEDIAN_RESULT_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_repeat_median_result_gate.json"
)
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_REPEAT_MEDIAN_REVIEW_GATE = gate_path(
    "public_results_packaging_refresh_after_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_repeat_median_review_gate.json"
)
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_REPEAT_MEDIAN_GATE = gate_path(
    "public_benchmark_pack_externalization_completion_after_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_repeat_median_gate.json"
)
NEXT_MEASUREMENT_SELECTION_AFTER_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_REPEAT_MEDIAN_PUBLIC_PACK_REFRESH_GATE = gate_path(
    "next_measurement_selection_after_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_repeat_median_public_pack_refresh_gate.json"
)
DEFINE_FILELIST_SHAPE_BREADTH_GPU_ALLOCATION_POLICY_BROADER_SHAPE_SWEEP_POLICY_GATE = gate_path(
    "define_filelist_shape_breadth_gpu_allocation_policy_broader_shape_sweep_policy_gate.json"
)
__all__ = [
    name
    for name in globals()
    if not name.startswith("_")
]
