import json
from pathlib import Path

from tests.contract.full_ita_mha_larger_paged_kv_next_resources import *  # noqa: F403
from tests.contract.full_ita_mha_larger_paged_kv_next_runtime_gates import *  # noqa: F403


REPO_ROOT = Path(__file__).resolve().parents[2]
SCALING_GATES = REPO_ROOT / "config" / "scaling_gates"
REPORTS = REPO_ROOT / "reports"
SLICE_LAUNCH_TEMPLATES = REPO_ROOT / "config" / "slice_launch_templates"
ITA_OVERLAY_SRC = REPO_ROOT / "overlays" / "ITA" / "src"
ITA_OVERLAY_TESTS = REPO_ROOT / "overlays" / "ITA" / "tests"
NVDLA_OVERLAY_ROOT = REPO_ROOT / "overlays" / "rtlmeter" / "designs" / "NVDLA"


def gate_path(filename: str) -> Path:
    return SCALING_GATES / filename


def report_path(filename: str) -> Path:
    return REPORTS / filename


def template_path(filename: str) -> Path:
    return SLICE_LAUNCH_TEMPLATES / filename


def ita_src_path(filename: str) -> Path:
    return ITA_OVERLAY_SRC / filename


def ita_test_path(filename: str) -> Path:
    return ITA_OVERLAY_TESTS / filename


def read_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def read_selection() -> object:
    import sys

    tools_dir = REPO_ROOT / "src" / "tools"
    tools_s = str(tools_dir)
    if tools_s not in sys.path:
        sys.path.insert(0, tools_s)
    import selection_state

    return selection_state.load_selection(REPO_ROOT)


def read_combined_docs(*paths: Path) -> str:
    selected_paths = paths or (README, STATUS, ROADMAP, RESULTS)
    return "\n".join(path.read_text(encoding="utf-8") for path in selected_paths)


CURRENT_PRIORITY = "run_config_generation_validation_breadth_execution_gate"
CURRENT_PRIORITY_SOURCE_ARTIFACT = (
    "config/scaling_gates/"
    "config_generation_validation_breadth_execution_gate.json"
)


NEXT_GATE = gate_path("neural_network_rtl_full_ita_mha_and_larger_paged_kv_next_gate.json")
LARGE_KV_GATE = gate_path("neural_network_rtl_paged_kv_cache_large_scaleup_gate.json")
LARGE_KV_REVIEW_GATE = gate_path("neural_network_rtl_paged_kv_cache_large_review_gate.json")
FULL_ITA_MHA_AUDIT_GATE = gate_path("neural_network_rtl_full_ita_mha_dependency_audit_gate.json")
FULL_ITA_MHA_BENCHMARK_GATE = gate_path("neural_network_rtl_full_ita_mha_first_hybrid_benchmark_gate.json")
GOAL_REVIEW_GATE = gate_path("neural_network_rtl_full_ita_mha_larger_paged_kv_goal_review_gate.json")
PAGED_ATTENTION_GATE = gate_path("neural_network_rtl_paged_attention_kv_score_harness_gate.json")
COMPLETION_AUDIT = gate_path("full_ita_mha_larger_paged_attention_kv_goal_completion_audit.json")
MODERN_LLM_COMPLETION_AUDIT = gate_path("modern_llm_serving_rtl_hybrid_conditions_goal_completion_audit.json")
PUBLIC_RESULTS_GATE = gate_path("public_results_packaging_gate.json")
PUBLIC_RESULTS_MHA_REFRESH_GATE = gate_path("public_results_packaging_refresh_after_pulp_ita_mha_shape_expansion_gate.json")
PUBLIC_RESULTS_PERSISTENT_REPEAT_MEDIAN_REFRESH_GATE = gate_path("public_results_packaging_refresh_after_persistent_resident_repeat_median_gate.json")
PUBLIC_BENCHMARK_PACK_COMPLETION_AUDIT = gate_path("public_benchmark_pack_goal_completion_audit.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_AUDIT = gate_path("public_benchmark_pack_externalization_readiness_audit.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_GATE = gate_path("public_benchmark_pack_externalization_completion_gate.json")
NEXT_MEASUREMENT_GOAL_SELECTION_GATE = gate_path("next_measurement_goal_selection_after_public_pack_readiness_gate.json")
NEXT_MEASUREMENT_AFTER_PUBLIC_PACK_EXTERNALIZATION_GATE = gate_path("next_measurement_selection_after_public_benchmark_pack_externalization_gate.json")
PAGED_ATTENTION_KV_CACHE_SCALE_UP_MEASUREMENT_GATE = gate_path("paged_attention_kv_cache_scale_up_measurement_gate.json")
PAGED_ATTENTION_KV_CACHE_SCALE_UP_MEASUREMENT_REVIEW_GATE = gate_path("paged_attention_kv_cache_scale_up_measurement_review_gate.json")
PAGED_ATTENTION_KV_CACHE_TIMING_SUMMARY_GATE = gate_path("paged_attention_kv_cache_timing_summary_gate.json")
PAGED_ATTENTION_KV_CACHE_TIMING_SUMMARY_REVIEW_GATE = gate_path("paged_attention_kv_cache_timing_summary_review_gate.json")
PUBLIC_RESULTS_PAGED_ATTENTION_KV_TIMING_REFRESH_GATE = gate_path("public_results_packaging_refresh_after_paged_attention_kv_cache_timing_summary_gate.json")
PUBLIC_PACK_COMPLETION_AFTER_PAGED_ATTENTION_KV_TIMING_REFRESH_GATE = gate_path("public_benchmark_pack_externalization_completion_after_paged_attention_kv_cache_timing_summary_gate.json")
NEXT_MEASUREMENT_AFTER_PAGED_ATTENTION_KV_TIMING_REFRESH_GATE = gate_path("next_measurement_selection_after_paged_attention_kv_cache_timing_refresh_gate.json")
PAGED_ATTENTION_KV_CACHE_REPEAT_MEDIAN_TIMING_GATE = gate_path("paged_attention_kv_cache_repeat_median_timing_gate.json")
PAGED_ATTENTION_KV_CACHE_REPEAT_MEDIAN_WORKFLOW_GATE = gate_path("paged_attention_kv_cache_repeat_median_workflow_gate.json")
PAGED_ATTENTION_KV_CACHE_REPEAT_MEDIAN_MEASUREMENT_GATE = gate_path("paged_attention_kv_cache_repeat_median_measurement_gate.json")
PAGED_ATTENTION_KV_CACHE_REPEAT_MEDIAN_REVIEW_GATE = gate_path("paged_attention_kv_cache_repeat_median_review_gate.json")
PUBLIC_RESULTS_PAGED_ATTENTION_KV_REPEAT_MEDIAN_REFRESH_GATE = gate_path("public_results_packaging_refresh_after_paged_attention_kv_cache_repeat_median_gate.json")
PUBLIC_PACK_COMPLETION_AFTER_PAGED_ATTENTION_KV_REPEAT_MEDIAN_REFRESH_GATE = gate_path("public_benchmark_pack_externalization_completion_after_paged_attention_kv_cache_repeat_median_gate.json")
NEXT_MEASUREMENT_AFTER_PAGED_ATTENTION_KV_REPEAT_MEDIAN_REFRESH_GATE = gate_path("next_measurement_selection_after_paged_attention_kv_cache_repeat_median_refresh_gate.json")
CONFIG_GENERATION_VALIDATION_BREADTH_GATE = gate_path("config_generation_validation_breadth_gate.json")
CONFIG_GENERATION_VALIDATION_BREADTH_DRY_RUN_GATE = gate_path("config_generation_validation_breadth_dry_run_gate.json")
CONFIG_GENERATION_VALIDATION_BREADTH_DRY_RUN_REVIEW_GATE = gate_path("config_generation_validation_breadth_dry_run_review_gate.json")
CONFIG_GENERATION_VALIDATION_BREADTH_EXECUTION_GATE = gate_path("config_generation_validation_breadth_execution_gate.json")
CONFIG_GENERATION_VALIDATION_BREADTH_EXECUTION_RESULT_GATE = gate_path("config_generation_validation_breadth_execution_result_gate.json")
CONFIG_GENERATION_VALIDATION_BREADTH_EXECUTION_REVIEW_GATE = gate_path("config_generation_validation_breadth_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_CONFIG_GENERATION_VALIDATION_BREADTH_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_config_generation_validation_breadth_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_CONFIG_GENERATION_VALIDATION_BREADTH_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_config_generation_validation_breadth_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_CONFIG_GENERATION_VALIDATION_BREADTH_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_config_generation_validation_breadth_public_pack_refresh_gate.json")
CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_GATE = gate_path("config_generation_validation_shape_breadth_gate.json")
CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_DRY_RUN_GATE = gate_path("config_generation_validation_shape_breadth_dry_run_gate.json")
CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_DRY_RUN_REVIEW_GATE = gate_path("config_generation_validation_shape_breadth_dry_run_review_gate.json")
CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_EXECUTION_GATE = gate_path("config_generation_validation_shape_breadth_execution_gate.json")
CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_EXECUTION_RESULT_GATE = gate_path("config_generation_validation_shape_breadth_execution_result_gate.json")
CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_EXECUTION_REVIEW_GATE = gate_path("config_generation_validation_shape_breadth_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_config_generation_validation_shape_breadth_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_config_generation_validation_shape_breadth_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_CONFIG_GENERATION_VALIDATION_SHAPE_BREADTH_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_config_generation_validation_shape_breadth_public_pack_refresh_gate.json")
CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_GATE = gate_path("config_generation_validation_additional_targets_gate.json")
CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_DRY_RUN_GATE = gate_path("config_generation_validation_additional_targets_dry_run_gate.json")
CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_DRY_RUN_REVIEW_GATE = gate_path("config_generation_validation_additional_targets_dry_run_review_gate.json")
CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_EXECUTION_GATE = gate_path("config_generation_validation_additional_targets_execution_gate.json")
CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_EXECUTION_RESULT_GATE = gate_path("config_generation_validation_additional_targets_execution_result_gate.json")
CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_EXECUTION_REVIEW_GATE = gate_path("config_generation_validation_additional_targets_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_config_generation_validation_additional_targets_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_config_generation_validation_additional_targets_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_CONFIG_GENERATION_VALIDATION_ADDITIONAL_TARGETS_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_config_generation_validation_additional_targets_public_pack_refresh_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_GATE = gate_path("tlul_template_schema_normalization_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_IMPLEMENTATION_GATE = gate_path("tlul_template_schema_normalization_implementation_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_IMPLEMENTATION_REVIEW_GATE = gate_path("tlul_template_schema_normalization_implementation_review_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EXECUTION_GATE = gate_path("tlul_template_schema_normalization_execution_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EXECUTION_RESULT_GATE = gate_path("tlul_template_schema_normalization_execution_result_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EXECUTION_REVIEW_GATE = gate_path("tlul_template_schema_normalization_execution_review_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_GATE = gate_path("tlul_template_schema_normalization_breadth_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_DRY_RUN_GATE = gate_path("tlul_template_schema_normalization_breadth_dry_run_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_DRY_RUN_REVIEW_GATE = gate_path("tlul_template_schema_normalization_breadth_dry_run_review_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_EXECUTION_GATE = gate_path("tlul_template_schema_normalization_breadth_execution_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_EXECUTION_RESULT_GATE = gate_path("tlul_template_schema_normalization_breadth_execution_result_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_EXECUTION_REVIEW_GATE = gate_path("tlul_template_schema_normalization_breadth_execution_review_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_PUBLIC_PACK_REFRESH_GATE = gate_path("tlul_template_schema_normalization_breadth_public_pack_refresh_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_GATE = gate_path("public_benchmark_pack_externalization_completion_after_tlul_template_schema_normalization_breadth_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_BREADTH_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_tlul_template_schema_normalization_breadth_public_pack_refresh_gate.json")
TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_GATE = gate_path("tlul_legacy_clock_reset_metadata_matrix_gate.json")
TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_DRY_RUN_GATE = gate_path("tlul_legacy_clock_reset_metadata_matrix_dry_run_gate.json")
TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_DRY_RUN_REVIEW_GATE = gate_path("tlul_legacy_clock_reset_metadata_matrix_dry_run_review_gate.json")
TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_EXECUTION_GATE = gate_path("tlul_legacy_clock_reset_metadata_matrix_execution_gate.json")
TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_EXECUTION_RESULT_GATE = gate_path("tlul_legacy_clock_reset_metadata_matrix_execution_result_gate.json")
TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_EXECUTION_REVIEW_GATE = gate_path("tlul_legacy_clock_reset_metadata_matrix_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_tlul_legacy_clock_reset_metadata_matrix_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_tlul_legacy_clock_reset_metadata_matrix_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_TLUL_LEGACY_CLOCK_RESET_METADATA_MATRIX_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_tlul_legacy_clock_reset_metadata_matrix_public_pack_refresh_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_GATE = gate_path("tlul_template_schema_normalization_more_breadth_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_DRY_RUN_GATE = gate_path("tlul_template_schema_normalization_more_breadth_dry_run_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_DRY_RUN_REVIEW_GATE = gate_path("tlul_template_schema_normalization_more_breadth_dry_run_review_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_EXECUTION_GATE = gate_path("tlul_template_schema_normalization_more_breadth_execution_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_EXECUTION_RESULT_GATE = gate_path("tlul_template_schema_normalization_more_breadth_execution_result_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_EXECUTION_REVIEW_GATE = gate_path("tlul_template_schema_normalization_more_breadth_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_tlul_template_schema_normalization_more_breadth_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_tlul_template_schema_normalization_more_breadth_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_MORE_BREADTH_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_tlul_template_schema_normalization_more_breadth_public_pack_refresh_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_GATE = gate_path("tlul_template_schema_normalization_even_more_breadth_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_DRY_RUN_GATE = gate_path("tlul_template_schema_normalization_even_more_breadth_dry_run_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_DRY_RUN_REVIEW_GATE = gate_path("tlul_template_schema_normalization_even_more_breadth_dry_run_review_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_EXECUTION_GATE = gate_path("tlul_template_schema_normalization_even_more_breadth_execution_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_EXECUTION_RESULT_GATE = gate_path("tlul_template_schema_normalization_even_more_breadth_execution_result_gate.json")
TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_EXECUTION_REVIEW_GATE = gate_path("tlul_template_schema_normalization_even_more_breadth_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_tlul_template_schema_normalization_even_more_breadth_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_tlul_template_schema_normalization_even_more_breadth_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_TLUL_TEMPLATE_SCHEMA_NORMALIZATION_EVEN_MORE_BREADTH_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_tlul_template_schema_normalization_even_more_breadth_public_pack_refresh_gate.json")
CONFIG_GENERATION_VALIDATION_FOLLOWUP_GATE = gate_path("config_generation_validation_followup_gate.json")
CONFIG_GENERATION_VALIDATION_FOLLOWUP_DRY_RUN_GATE = gate_path("config_generation_validation_followup_dry_run_gate.json")
CONFIG_GENERATION_VALIDATION_FOLLOWUP_DRY_RUN_REVIEW_GATE = gate_path("config_generation_validation_followup_dry_run_review_gate.json")
CONFIG_GENERATION_VALIDATION_FOLLOWUP_EXECUTION_GATE = gate_path("config_generation_validation_followup_execution_gate.json")
CONFIG_GENERATION_VALIDATION_FOLLOWUP_EXECUTION_RESULT_GATE = gate_path("config_generation_validation_followup_execution_result_gate.json")
CONFIG_GENERATION_VALIDATION_FOLLOWUP_EXECUTION_REVIEW_GATE = gate_path("config_generation_validation_followup_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_CONFIG_GENERATION_VALIDATION_FOLLOWUP_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_config_generation_validation_followup_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_CONFIG_GENERATION_VALIDATION_FOLLOWUP_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_config_generation_validation_followup_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_CONFIG_GENERATION_VALIDATION_FOLLOWUP_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_config_generation_validation_followup_public_pack_refresh_gate.json")
TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_REVIEW_GATE = gate_path("tlul_template_schema_metadata_invariant_review_gate.json")
TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_REVIEW_DRY_RUN_GATE = gate_path("tlul_template_schema_metadata_invariant_review_dry_run_gate.json")
TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_REVIEW_DRY_RUN_REVIEW_GATE = gate_path("tlul_template_schema_metadata_invariant_review_dry_run_review_gate.json")
TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_EXECUTION_GATE = gate_path("tlul_template_schema_metadata_invariant_execution_gate.json")
TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_EXECUTION_RESULT_GATE = gate_path("tlul_template_schema_metadata_invariant_execution_result_gate.json")
TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_EXECUTION_REVIEW_GATE = gate_path("tlul_template_schema_metadata_invariant_execution_review_gate.json")
PUBLIC_RESULTS_PACKAGING_REFRESH_AFTER_TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_EXECUTION_GATE = gate_path("public_results_packaging_refresh_after_tlul_template_schema_metadata_invariant_execution_gate.json")
PUBLIC_BENCHMARK_PACK_EXTERNALIZATION_COMPLETION_AFTER_TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_EXECUTION_GATE = gate_path("public_benchmark_pack_externalization_completion_after_tlul_template_schema_metadata_invariant_execution_gate.json")
NEXT_MEASUREMENT_SELECTION_AFTER_TLUL_TEMPLATE_SCHEMA_METADATA_INVARIANT_PUBLIC_PACK_REFRESH_GATE = gate_path("next_measurement_selection_after_tlul_template_schema_metadata_invariant_public_pack_refresh_gate.json")
__all__ = [
    name
    for name in globals()
    if not name.startswith("_")
]
