third_party/common_cells/src/cf_math_pkg.sv
third_party/common_cells/src/lzc.sv
third_party/common_cells/src/fifo_v3.sv
overlays/ITA/src/pulp_ita_cluster_clock_gating_sim.sv
overlays/ITA/src/pulp_ita_tc_sram_sim.sv
third_party/ITA/src/ita_package.sv
third_party/ITA/src/ita_controller.sv
third_party/ITA/src/ita_input_sampler.sv
third_party/ITA/src/ita_inp1_mux.sv
third_party/ITA/src/ita_inp2_mux.sv
third_party/ITA/src/ita_dotp.sv
third_party/ITA/src/ita_sumdotp.sv
third_party/ITA/src/ita_accumulator.sv
third_party/ITA/src/ita_max_finder.sv
third_party/ITA/src/ita_register_file_1w_multi_port_read.sv
third_party/ITA/src/ita_softmax.sv
third_party/ITA/src/ita_serdiv.sv
third_party/ITA/src/ita_softmax_top.sv
third_party/ITA/src/ita_requantization_controller.sv
third_party/ITA/src/ita_requantizer.sv
third_party/ITA/src/ita_gelu.sv
third_party/ITA/src/ita_relu.sv
third_party/ITA/src/ita_activation.sv
third_party/ITA/src/ita_fifo_controller.sv
third_party/ITA/src/ita_output_controller.sv
third_party/ITA/src/ita_weight_controller.sv
third_party/ITA/src/ita_register_file_1w_multi_port_read_we.sv
third_party/ITA/src/ita.sv
overlays/ITA/src/pulp_ita_mha_gpu_cov_tb.sv
