from __future__ import annotations

import re


NVPTX_DATALAYOUT = "e-i64:64-i128:128-v16:16-v32:32-n16:32:64"
NVPTX_TRIPLE = "nvptx64-nvidia-cuda"


def header_lines(*, storage_size: int, eval_fn: str, vlsyms_offset: int | None) -> list[str]:
    lines = [
        "; NVPTX GPU kernel - auto-generated by gen_vl_gpu_kernel.py",
        f"; Storage size: {storage_size} bytes / state",
        f"; eval function: @{eval_fn}",
    ]
    if vlsyms_offset is not None:
        lines.append(f"; vlSymsp offset: {vlsyms_offset} (initialized to @fake_syms_buf)")
    lines.extend(["", f'target datalayout = "{NVPTX_DATALAYOUT}"', f'target triple = "{NVPTX_TRIPLE}"', ""])
    return lines


def nvvm_decl_lines() -> list[str]:
    return [
        "declare i32 @llvm.nvvm.read.ptx.sreg.tid.x()",
        "declare i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()",
        "declare i32 @llvm.nvvm.read.ptx.sreg.ntid.x()",
        "declare i32 @__gxx_personality_v0(...)",
        "",
    ]


def init_replication_kernel_lines() -> list[str]:
    return [
        "; === GPU kernel: init-state replication ===",
        "define void @vl_replicate_init_state_gpu(ptr %storage_base, ptr %init_state, i64 %storage_bytes, i64 %total_bytes) {",
        "entry:",
        "  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()",
        "  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()",
        "  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()",
        "  %gid_mul = mul i32 %bid, %bdim",
        "  %gid32   = add i32 %gid_mul, %tid",
        "  %gid = zext i32 %gid32 to i64",
        "  %in_range = icmp ult i64 %gid, %total_bytes",
        "  br i1 %in_range, label %body, label %exit",
        "",
        "body:",
        "  %src_off = urem i64 %gid, %storage_bytes",
        "  %src = getelementptr inbounds i8, ptr %init_state, i64 %src_off",
        "  %value = load i8, ptr %src, align 1",
        "  %dst = getelementptr inbounds i8, ptr %storage_base, i64 %gid",
        "  store i8 %value, ptr %dst, align 1",
        "  br label %exit",
        "",
        "exit:",
        "  ret void",
        "}",
        "",
    ]


def batch_kernel_lines(*, storage_size: int, eval_fn: str, vlsyms_offset: int | None) -> list[str]:
    lines = [
        "; === GPU kernel: batch_gpu ===",
        "define void @vl_eval_batch_gpu(ptr %storage_base, i32 %nstates) {",
        "entry:",
        "  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()",
        "  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()",
        "  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()",
        "  %gid_mul = mul i32 %bid, %bdim",
        "  %gid32   = add i32 %gid_mul, %tid",
        "  %in_range = icmp ult i32 %gid32, %nstates",
        "  br i1 %in_range, label %body, label %exit",
        "",
        "body:",
        "  %gid    = zext i32 %gid32 to i64",
        f"  %stride = add i64 {storage_size}, 0",
        "  %offset = mul i64 %gid, %stride",
        "  %state_ptr = getelementptr inbounds i8, ptr %storage_base, i64 %offset",
    ]
    if vlsyms_offset is not None:
        lines.append(f"  %vlsyms_gep = getelementptr inbounds i8, ptr %state_ptr, i64 {vlsyms_offset}")
        lines.append("  store ptr @fake_syms_buf, ptr %vlsyms_gep, align 8")
    lines.extend([f"  call void @{eval_fn}(ptr %state_ptr)", "  br label %exit", "", "exit:", "  ret void", "}", ""])
    return lines


def patch_schedule_kernel_lines() -> list[str]:
    return [
        "; === GPU kernel: resident patch schedule ===",
        "define void @vl_apply_patch_schedule_gpu(ptr %storage_base, ptr %patch_offsets, ptr %patch_values, i32 %patch_count) {",
        "entry:",
        "  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()",
        "  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()",
        "  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()",
        "  %gid_mul = mul i32 %bid, %bdim",
        "  %gid32   = add i32 %gid_mul, %tid",
        "  %in_range = icmp ult i32 %gid32, %patch_count",
        "  br i1 %in_range, label %body, label %exit",
        "",
        "body:",
        "  %gid = zext i32 %gid32 to i64",
        "  %offset_ptr = getelementptr inbounds i64, ptr %patch_offsets, i64 %gid",
        "  %off = load i64, ptr %offset_ptr, align 8",
        "  %value_ptr = getelementptr inbounds i8, ptr %patch_values, i64 %gid",
        "  %value = load i8, ptr %value_ptr, align 1",
        "  %dst = getelementptr inbounds i8, ptr %storage_base, i64 %off",
        "  store i8 %value, ptr %dst, align 1",
        "  br label %exit",
        "",
        "exit:",
        "  ret void",
        "}",
        "",
    ]


def metadata_lines(text: str) -> list[str]:
    lines: list[str] = []
    max_id = -1
    for line in text.splitlines():
        if re.match(r"^!\d+\s*=", line):
            mid = int(re.match(r"^!(\d+)", line).group(1))
            max_id = max(max_id, mid)
            lines.append(line)
    lines.append("")
    kernel_id = max_id + 1
    patch_kernel_id = kernel_id + 1
    init_replication_kernel_id = kernel_id + 2
    lines.append(f'!{kernel_id} = !{{ptr @vl_eval_batch_gpu, !"kernel", i32 1}}')
    lines.append(f'!{patch_kernel_id} = !{{ptr @vl_apply_patch_schedule_gpu, !"kernel", i32 1}}')
    lines.append(f'!{init_replication_kernel_id} = !{{ptr @vl_replicate_init_state_gpu, !"kernel", i32 1}}')
    lines.append(f"!nvvm.annotations = !{{!{kernel_id}, !{patch_kernel_id}, !{init_replication_kernel_id}}}")
    return lines
