#!/usr/bin/env python3
"""
gen_vl_gpu_kernel.py
Verilator --cc + clang++ -emit-llvm の merged.ll から
NVPTX GPU カーネルを生成する。

戦略:
  1. _eval から到達する define 済み関数だけ抽出
  2. 外部関数 (VL_FATAL_MT 等) を no-op stub に置き換え
  3. NVPTX ターゲット設定
  4. AoS-strided カーネルを追加
       thread i → _eval(base + i * storage_size)

Usage:
  python3 gen_vl_gpu_kernel.py <merged.ll> <storage_size> [out_gpu.ll]
"""

import re
import sys
from pathlib import Path

from llvm_ir_parse import extract_functions, reachable_from, external_calls
from llvm_stub_gen import make_no_op_stub
from vl_runtime_filter import is_runtime, detect_syms_buffer_size, detect_vlsyms_offset

NVPTX_DATALAYOUT = 'e-i64:64-i128:128-v16:16-v32:32-n16:32:64'
NVPTX_TRIPLE     = 'nvptx64-nvidia-cuda'


def generate_gpu_ll(merged_ll_path: Path, storage_size: int) -> str:
    text = merged_ll_path.read_text(encoding='utf-8')

    all_funcs = extract_functions(text)

    # _eval 関数名を特定 (___024root___eval で終わる)
    eval_fn = None
    for name in all_funcs:
        if re.search(r'___024root___evalP', name) and '___eval_' not in name:
            eval_fn = name
            break
    if eval_fn is None:
        for name in all_funcs:
            if '_eval' in name and re.search(
                r'define\s+void\s+@' + re.escape(name) + r'\s*\(ptr', text
            ):
                eval_fn = name
                break
    if eval_fn is None:
        raise RuntimeError('_eval 関数が見つかりません')
    print(f'eval 関数: @{eval_fn}')

    needed_raw = reachable_from(eval_fn, all_funcs)
    print(f'到達可能な define 関数 (raw): {len(needed_raw)} 個')

    needed = {n for n in needed_raw if not is_runtime(n, all_funcs.get(n, ''))}
    forced_stubs = needed_raw - needed
    print(f'到達可能な define 関数 (GPU対象): {len(needed)} 個')
    if forced_stubs:
        print(f'ランタイム関数を stub 化: {len(forced_stubs)} 個')

    ext = external_calls(needed, all_funcs) | forced_stubs
    print(f'stub 必要な外部関数: {len(ext)} 個')

    vlsyms_offset = detect_vlsyms_offset(text)
    syms_buffer_size = detect_syms_buffer_size(text) if vlsyms_offset is not None else None
    if vlsyms_offset is not None:
        print(f'vlSymsp オフセット: {vlsyms_offset} bytes (fake_syms_buf で null-safe 化)')
    else:
        print('vlSymsp オフセット: 未検出 (vlSyms 初期化スキップ)')

    lines = []
    lines.append('; NVPTX GPU kernel — auto-generated by gen_vl_gpu_kernel.py')
    lines.append(f'; Storage size: {storage_size} bytes / state')
    lines.append(f'; eval function: @{eval_fn}')
    if vlsyms_offset is not None:
        lines.append(f'; vlSymsp offset: {vlsyms_offset} (initialized to @fake_syms_buf)')
    lines.append('')
    lines.append(f'target datalayout = "{NVPTX_DATALAYOUT}"')
    lines.append(f'target triple = "{NVPTX_TRIPLE}"')
    lines.append('')

    # 型定義
    for line in text.splitlines():
        if re.match(r'^%.*=\s*type\s', line):
            lines.append(line)
    lines.append('')

    # fake_syms_buf: ico_sequent / nba_comb の vlSyms デリファレンスを null-safe にする
    if vlsyms_offset is not None:
        lines.append(
            f'@fake_syms_buf = internal global [{syms_buffer_size} x i8] zeroinitializer, align 64'
        )
        lines.append('')

    # グローバル変数定義マップ (@.str.* 以外)
    global_defs: dict[str, str] = {}
    for line in text.splitlines():
        m = re.match(r'^(@[\w.]+)\s*=', line)
        if m and not re.match(r'^@\.str', line):
            global_defs[m.group(1)] = line

    # 文字列定数 (@.str.*)
    for line in text.splitlines():
        if re.match(r'^@\.str', line):
            lines.append(line)

    # switch table 等、関数本体から参照される非関数グローバル
    needed_globals: set[str] = set()
    for fn_name in needed:
        for ref in re.findall(r'@([\w.]+)', all_funcs[fn_name]):
            gname = f'@{ref}'
            if gname in global_defs:
                needed_globals.add(gname)
    if needed_globals:
        lines.append('; referenced globals (switch tables, const data, ...)')
        for gname in sorted(needed_globals):
            lines.append(global_defs[gname])
    lines.append('')

    lines.append('declare i32 @llvm.nvvm.read.ptx.sreg.tid.x()')
    lines.append('declare i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()')
    lines.append('declare i32 @llvm.nvvm.read.ptx.sreg.ntid.x()')
    # lowerinvoke + vl-strip-x86-attrs が personality を除去するまでの参照先として必要
    lines.append('declare i32 @__gxx_personality_v0(...)')
    lines.append('')

    lines.append('; === GPU kernel: init-state replication ===')
    lines.append('define void @vl_replicate_init_state_gpu(ptr %storage_base, ptr %init_state, i64 %storage_bytes, i64 %total_bytes) {')
    lines.append('entry:')
    lines.append('  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()')
    lines.append('  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()')
    lines.append('  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()')
    lines.append('  %gid_mul = mul i32 %bid, %bdim')
    lines.append('  %gid32   = add i32 %gid_mul, %tid')
    lines.append('  %gid = zext i32 %gid32 to i64')
    lines.append('  %in_range = icmp ult i64 %gid, %total_bytes')
    lines.append('  br i1 %in_range, label %body, label %exit')
    lines.append('')
    lines.append('body:')
    lines.append('  %src_off = urem i64 %gid, %storage_bytes')
    lines.append('  %src = getelementptr inbounds i8, ptr %init_state, i64 %src_off')
    lines.append('  %value = load i8, ptr %src, align 1')
    lines.append('  %dst = getelementptr inbounds i8, ptr %storage_base, i64 %gid')
    lines.append('  store i8 %value, ptr %dst, align 1')
    lines.append('  br label %exit')
    lines.append('')
    lines.append('exit:')
    lines.append('  ret void')
    lines.append('}')
    lines.append('')

    # no-op stub
    for ext_fn in sorted(ext):
        lines.append(f'; stub: {ext_fn}')
        lines.append(make_no_op_stub(ext_fn, text))

    # 関数本体 (変換は opt --load-pass-plugin=VlGpuPasses.so で実施)
    for fn_name in sorted(needed):
        lines.append(all_funcs[fn_name])
        lines.append('')

    # AoS-strided GPU カーネル
    lines.append('; === GPU kernel: batch_gpu ===')
    lines.append(f'define void @vl_eval_batch_gpu(ptr %storage_base, i32 %nstates) {{')
    lines.append('entry:')
    lines.append('  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()')
    lines.append('  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()')
    lines.append('  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()')
    lines.append('  %gid_mul = mul i32 %bid, %bdim')
    lines.append('  %gid32   = add i32 %gid_mul, %tid')
    lines.append('  %in_range = icmp ult i32 %gid32, %nstates')
    lines.append('  br i1 %in_range, label %body, label %exit')
    lines.append('')
    lines.append('body:')
    lines.append('  %gid    = zext i32 %gid32 to i64')
    lines.append(f'  %stride = add i64 {storage_size}, 0')
    lines.append('  %offset = mul i64 %gid, %stride')
    lines.append('  %state_ptr = getelementptr inbounds i8, ptr %storage_base, i64 %offset')
    if vlsyms_offset is not None:
        lines.append(f'  %vlsyms_gep = getelementptr inbounds i8, ptr %state_ptr, i64 {vlsyms_offset}')
        lines.append('  store ptr @fake_syms_buf, ptr %vlsyms_gep, align 8')
    lines.append(f'  call void @{eval_fn}(ptr %state_ptr)')
    lines.append('  br label %exit')
    lines.append('')
    lines.append('exit:')
    lines.append('  ret void')
    lines.append('}')
    lines.append('')

    # Device-resident patch application kernel.
    #
    # The host runtime uploads compact patch offset/value arrays once before a
    # resident loop. For each logical step it launches this kernel with pointers
    # already advanced to that step's record slice, avoiding per-step HtoD patch
    # copies while keeping the existing --patch-script grammar.
    lines.append('; === GPU kernel: resident patch schedule ===')
    lines.append('define void @vl_apply_patch_schedule_gpu(ptr %storage_base, ptr %patch_offsets, ptr %patch_values, i32 %patch_count) {')
    lines.append('entry:')
    lines.append('  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()')
    lines.append('  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()')
    lines.append('  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()')
    lines.append('  %gid_mul = mul i32 %bid, %bdim')
    lines.append('  %gid32   = add i32 %gid_mul, %tid')
    lines.append('  %in_range = icmp ult i32 %gid32, %patch_count')
    lines.append('  br i1 %in_range, label %body, label %exit')
    lines.append('')
    lines.append('body:')
    lines.append('  %gid = zext i32 %gid32 to i64')
    lines.append('  %offset_ptr = getelementptr inbounds i64, ptr %patch_offsets, i64 %gid')
    lines.append('  %off = load i64, ptr %offset_ptr, align 8')
    lines.append('  %value_ptr = getelementptr inbounds i8, ptr %patch_values, i64 %gid')
    lines.append('  %value = load i8, ptr %value_ptr, align 1')
    lines.append('  %dst = getelementptr inbounds i8, ptr %storage_base, i64 %off')
    lines.append('  store i8 %value, ptr %dst, align 1')
    lines.append('  br label %exit')
    lines.append('')
    lines.append('exit:')
    lines.append('  ret void')
    lines.append('}')
    lines.append('')

    # Program-image initialization applies source-backed IAHB records once to
    # every state before resident eval. It intentionally reuses the offset/value
    # SoA shape from resident patch schedules, but expands across states inside
    # the kernel instead of launching once per logical step.
    lines.append('; === GPU kernel: program-image initialization ===')
    lines.append('define void @vl_apply_program_image_init_gpu(ptr %storage_base, ptr %record_offsets, ptr %record_values, i32 %record_count, i64 %storage_bytes, i32 %nstates) {')
    lines.append('entry:')
    lines.append('  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()')
    lines.append('  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()')
    lines.append('  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()')
    lines.append('  %gid_mul = mul i32 %bid, %bdim')
    lines.append('  %gid32   = add i32 %gid_mul, %tid')
    lines.append('  %gid = zext i32 %gid32 to i64')
    lines.append('  %record_count64 = zext i32 %record_count to i64')
    lines.append('  %nstates64 = zext i32 %nstates to i64')
    lines.append('  %total_records = mul i64 %record_count64, %nstates64')
    lines.append('  %in_range = icmp ult i64 %gid, %total_records')
    lines.append('  br i1 %in_range, label %body, label %exit')
    lines.append('')
    lines.append('body:')
    lines.append('  %state_idx = udiv i64 %gid, %record_count64')
    lines.append('  %record_idx = urem i64 %gid, %record_count64')
    lines.append('  %state_base_off = mul i64 %state_idx, %storage_bytes')
    lines.append('  %offset_ptr = getelementptr inbounds i64, ptr %record_offsets, i64 %record_idx')
    lines.append('  %record_off = load i64, ptr %offset_ptr, align 8')
    lines.append('  %value_ptr = getelementptr inbounds i8, ptr %record_values, i64 %record_idx')
    lines.append('  %value = load i8, ptr %value_ptr, align 1')
    lines.append('  %dst_off = add i64 %state_base_off, %record_off')
    lines.append('  %dst = getelementptr inbounds i8, ptr %storage_base, i64 %dst_off')
    lines.append('  store i8 %value, ptr %dst, align 1')
    lines.append('  br label %exit')
    lines.append('')
    lines.append('exit:')
    lines.append('  ret void')
    lines.append('}')
    lines.append('')

    # Word-packed program-image initialization uploads case.pat source words
    # once and expands the four IAHB memory lanes on device for each state.
    lines.append('; === GPU kernel: word-packed program-image initialization ===')
    lines.append('define void @vl_apply_program_image_words_gpu(ptr %storage_base, ptr %program_words, ptr %lane_base_offsets, i32 %word_count, i64 %storage_bytes, i32 %nstates) {')
    lines.append('entry:')
    lines.append('  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()')
    lines.append('  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()')
    lines.append('  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()')
    lines.append('  %gid_mul = mul i32 %bid, %bdim')
    lines.append('  %gid32   = add i32 %gid_mul, %tid')
    lines.append('  %gid = zext i32 %gid32 to i64')
    lines.append('  %word_count64 = zext i32 %word_count to i64')
    lines.append('  %nstates64 = zext i32 %nstates to i64')
    lines.append('  %total_words = mul i64 %word_count64, %nstates64')
    lines.append('  %in_range = icmp ult i64 %gid, %total_words')
    lines.append('  br i1 %in_range, label %body, label %exit')
    lines.append('')
    lines.append('body:')
    lines.append('  %state_idx = udiv i64 %gid, %word_count64')
    lines.append('  %word_idx = urem i64 %gid, %word_count64')
    lines.append('  %state_base_off = mul i64 %state_idx, %storage_bytes')
    lines.append('  %word_ptr = getelementptr inbounds i32, ptr %program_words, i64 %word_idx')
    lines.append('  %word = load i32, ptr %word_ptr, align 4')
    lines.append('  %ram0_shift = lshr i32 %word, 24')
    lines.append('  %ram0_byte = trunc i32 %ram0_shift to i8')
    lines.append('  %ram1_shift = lshr i32 %word, 16')
    lines.append('  %ram1_trunc = trunc i32 %ram1_shift to i8')
    lines.append('  %ram2_shift = lshr i32 %word, 8')
    lines.append('  %ram2_byte = trunc i32 %ram2_shift to i8')
    lines.append('  %ram3_byte = trunc i32 %word to i8')
    for lane in range(4):
        lines.append(f'  %lane{lane}_base_ptr = getelementptr inbounds i64, ptr %lane_base_offsets, i64 {lane}')
        lines.append(f'  %lane{lane}_base = load i64, ptr %lane{lane}_base_ptr, align 8')
        lines.append(f'  %lane{lane}_rel = add i64 %lane{lane}_base, %word_idx')
        lines.append(f'  %lane{lane}_dst_off = add i64 %state_base_off, %lane{lane}_rel')
        lines.append(f'  %lane{lane}_dst = getelementptr inbounds i8, ptr %storage_base, i64 %lane{lane}_dst_off')
    lines.append('  store i8 %ram0_byte, ptr %lane0_dst, align 1')
    lines.append('  store i8 %ram1_trunc, ptr %lane1_dst, align 1')
    lines.append('  store i8 %ram2_byte, ptr %lane2_dst, align 1')
    lines.append('  store i8 %ram3_byte, ptr %lane3_dst, align 1')
    lines.append('  br label %exit')
    lines.append('')
    lines.append('exit:')
    lines.append('  ret void')
    lines.append('}')
    lines.append('')

    # TBAA / prof メタデータ
    meta_lines = []
    max_id = -1
    for line in text.splitlines():
        if re.match(r'^!\d+\s*=', line):
            mid = int(re.match(r'^!(\d+)', line).group(1))
            max_id = max(max_id, mid)
            meta_lines.append(line)
    lines.extend(meta_lines)
    lines.append('')

    kernel_id = max_id + 1
    patch_kernel_id = kernel_id + 1
    init_replication_kernel_id = kernel_id + 2
    program_image_init_kernel_id = kernel_id + 3
    program_image_words_kernel_id = kernel_id + 4
    lines.append(f'!{kernel_id} = !{{ptr @vl_eval_batch_gpu, !"kernel", i32 1}}')
    lines.append(f'!{patch_kernel_id} = !{{ptr @vl_apply_patch_schedule_gpu, !"kernel", i32 1}}')
    lines.append(f'!{init_replication_kernel_id} = !{{ptr @vl_replicate_init_state_gpu, !"kernel", i32 1}}')
    lines.append(f'!{program_image_init_kernel_id} = !{{ptr @vl_apply_program_image_init_gpu, !"kernel", i32 1}}')
    lines.append(f'!{program_image_words_kernel_id} = !{{ptr @vl_apply_program_image_words_gpu, !"kernel", i32 1}}')
    lines.append(f'!nvvm.annotations = !{{!{kernel_id}, !{patch_kernel_id}, !{init_replication_kernel_id}, !{program_image_init_kernel_id}, !{program_image_words_kernel_id}}}')

    return '\n'.join(lines)


def main() -> None:
    if len(sys.argv) < 3:
        print(f'Usage: {sys.argv[0]} <merged.ll> <storage_size> [out_gpu.ll]')
        sys.exit(1)

    merged_ll  = Path(sys.argv[1])
    storage_sz = int(sys.argv[2])
    out_path   = Path(sys.argv[3]) if len(sys.argv) > 3 \
                 else merged_ll.parent / 'vl_batch_gpu.ll'

    gpu_ll = generate_gpu_ll(merged_ll, storage_sz)
    out_path.write_text(gpu_ll, encoding='utf-8')
    print(f'Written: {out_path}')


if __name__ == '__main__':
    main()
