from __future__ import annotations

import re


NVPTX_DATALAYOUT = "e-i64:64-i128:128-v16:16-v32:32-n16:32:64"
NVPTX_TRIPLE = "nvptx64-nvidia-cuda"


def header_lines(*, storage_size: int, eval_fn: str, vlsyms_offset: int | None) -> list[str]:
    lines = [
        "; NVPTX GPU kernel - auto-generated by gen_vl_gpu_kernel.py",
        f"; Storage size: {storage_size} bytes / state",
        f"; eval function: @{eval_fn}",
    ]
    if vlsyms_offset is not None:
        lines.append(f"; vlSymsp offset: {vlsyms_offset} (initialized to @fake_syms_buf)")
    lines.extend(["", f'target datalayout = "{NVPTX_DATALAYOUT}"', f'target triple = "{NVPTX_TRIPLE}"', ""])
    return lines


def nvvm_decl_lines() -> list[str]:
    return [
        "declare i32 @llvm.nvvm.read.ptx.sreg.tid.x()",
        "declare i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()",
        "declare i32 @llvm.nvvm.read.ptx.sreg.ntid.x()",
        "declare i32 @__gxx_personality_v0(...)",
        "",
    ]


def init_replication_kernel_lines() -> list[str]:
    return [
        "; === GPU kernel: init-state replication ===",
        "define void @vl_replicate_init_state_gpu(ptr %storage_base, ptr %init_state, i64 %storage_bytes, i64 %total_bytes) {",
        "entry:",
        "  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()",
        "  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()",
        "  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()",
        "  %gid_mul = mul i32 %bid, %bdim",
        "  %gid32   = add i32 %gid_mul, %tid",
        "  %gid = zext i32 %gid32 to i64",
        "  %in_range = icmp ult i64 %gid, %total_bytes",
        "  br i1 %in_range, label %body, label %exit",
        "",
        "body:",
        "  %src_off = urem i64 %gid, %storage_bytes",
        "  %src = getelementptr inbounds i8, ptr %init_state, i64 %src_off",
        "  %value = load i8, ptr %src, align 1",
        "  %dst = getelementptr inbounds i8, ptr %storage_base, i64 %gid",
        "  store i8 %value, ptr %dst, align 1",
        "  br label %exit",
        "",
        "exit:",
        "  ret void",
        "}",
        "",
    ]


def batch_kernel_lines(*, storage_size: int, eval_fn: str, vlsyms_offset: int | None) -> list[str]:
    lines = [
        "; === GPU kernel: batch_gpu ===",
        "define void @vl_eval_batch_gpu(ptr %storage_base, i32 %nstates) {",
        "entry:",
        "  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()",
        "  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()",
        "  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()",
        "  %gid_mul = mul i32 %bid, %bdim",
        "  %gid32   = add i32 %gid_mul, %tid",
        "  %in_range = icmp ult i32 %gid32, %nstates",
        "  br i1 %in_range, label %body, label %exit",
        "",
        "body:",
        "  %gid    = zext i32 %gid32 to i64",
        f"  %stride = add i64 {storage_size}, 0",
        "  %offset = mul i64 %gid, %stride",
        "  %state_ptr = getelementptr inbounds i8, ptr %storage_base, i64 %offset",
    ]
    if vlsyms_offset is not None:
        lines.append(f"  %vlsyms_gep = getelementptr inbounds i8, ptr %state_ptr, i64 {vlsyms_offset}")
        lines.append("  store ptr @fake_syms_buf, ptr %vlsyms_gep, align 8")
    lines.extend([f"  call void @{eval_fn}(ptr %state_ptr)", "  br label %exit", "", "exit:", "  ret void", "}", ""])
    return lines


def patch_schedule_kernel_lines() -> list[str]:
    return [
        "; === GPU kernel: resident patch schedule ===",
        "define void @vl_apply_patch_schedule_gpu(ptr %storage_base, ptr %patch_offsets, ptr %patch_values, i32 %patch_count) {",
        "entry:",
        "  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()",
        "  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()",
        "  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()",
        "  %gid_mul = mul i32 %bid, %bdim",
        "  %gid32   = add i32 %gid_mul, %tid",
        "  %in_range = icmp ult i32 %gid32, %patch_count",
        "  br i1 %in_range, label %body, label %exit",
        "",
        "body:",
        "  %gid = zext i32 %gid32 to i64",
        "  %offset_ptr = getelementptr inbounds i64, ptr %patch_offsets, i64 %gid",
        "  %off = load i64, ptr %offset_ptr, align 8",
        "  %value_ptr = getelementptr inbounds i8, ptr %patch_values, i64 %gid",
        "  %value = load i8, ptr %value_ptr, align 1",
        "  %dst = getelementptr inbounds i8, ptr %storage_base, i64 %off",
        "  store i8 %value, ptr %dst, align 1",
        "  br label %exit",
        "",
        "exit:",
        "  ret void",
        "}",
        "",
    ]


def feedback_edge_kernel_lines() -> list[str]:
    return [
        "; === GPU kernel: resident byte feedback edges ===",
        "define void @vl_apply_feedback_edges_gpu(ptr %storage_base, ptr %src_offsets, ptr %dst_offsets, i32 %edge_count, i64 %storage_stride, i32 %nstates) {",
        "entry:",
        "  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()",
        "  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()",
        "  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()",
        "  %gid_mul = mul i32 %bid, %bdim",
        "  %gid32   = add i32 %gid_mul, %tid",
        "  %total = mul i32 %edge_count, %nstates",
        "  %in_range = icmp ult i32 %gid32, %total",
        "  br i1 %in_range, label %body, label %exit",
        "",
        "body:",
        "  %edge_idx = urem i32 %gid32, %edge_count",
        "  %state_idx32 = udiv i32 %gid32, %edge_count",
        "  %edge_idx64 = zext i32 %edge_idx to i64",
        "  %state_idx = zext i32 %state_idx32 to i64",
        "  %state_base = mul i64 %state_idx, %storage_stride",
        "  %src_offset_ptr = getelementptr inbounds i64, ptr %src_offsets, i64 %edge_idx64",
        "  %src_local = load i64, ptr %src_offset_ptr, align 8",
        "  %dst_offset_ptr = getelementptr inbounds i64, ptr %dst_offsets, i64 %edge_idx64",
        "  %dst_local = load i64, ptr %dst_offset_ptr, align 8",
        "  %src_off = add i64 %state_base, %src_local",
        "  %dst_off = add i64 %state_base, %dst_local",
        "  %src = getelementptr inbounds i8, ptr %storage_base, i64 %src_off",
        "  %value = load i8, ptr %src, align 1",
        "  %dst = getelementptr inbounds i8, ptr %storage_base, i64 %dst_off",
        "  store i8 %value, ptr %dst, align 1",
        "  br label %exit",
        "",
        "exit:",
        "  ret void",
        "}",
        "",
    ]


def feedback_increment_kernel_lines() -> list[str]:
    return [
        "; === GPU kernel: resident byte feedback increments ===",
        "define void @vl_apply_feedback_increments_gpu(ptr %storage_base, ptr %offsets, ptr %deltas, i32 %increment_count, i64 %storage_stride, i32 %nstates) {",
        "entry:",
        "  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()",
        "  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()",
        "  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()",
        "  %gid_mul = mul i32 %bid, %bdim",
        "  %gid32   = add i32 %gid_mul, %tid",
        "  %total = mul i32 %increment_count, %nstates",
        "  %in_range = icmp ult i32 %gid32, %total",
        "  br i1 %in_range, label %body, label %exit",
        "",
        "body:",
        "  %inc_idx = urem i32 %gid32, %increment_count",
        "  %state_idx32 = udiv i32 %gid32, %increment_count",
        "  %inc_idx64 = zext i32 %inc_idx to i64",
        "  %state_idx = zext i32 %state_idx32 to i64",
        "  %state_base = mul i64 %state_idx, %storage_stride",
        "  %offset_ptr = getelementptr inbounds i64, ptr %offsets, i64 %inc_idx64",
        "  %local = load i64, ptr %offset_ptr, align 8",
        "  %delta_ptr = getelementptr inbounds i8, ptr %deltas, i64 %inc_idx64",
        "  %delta = load i8, ptr %delta_ptr, align 1",
        "  %off = add i64 %state_base, %local",
        "  %dst = getelementptr inbounds i8, ptr %storage_base, i64 %off",
        "  %old = load i8, ptr %dst, align 1",
        "  %new = add i8 %old, %delta",
        "  store i8 %new, ptr %dst, align 1",
        "  br label %exit",
        "",
        "exit:",
        "  ret void",
        "}",
        "",
    ]


def feedback_set_kernel_lines() -> list[str]:
    return [
        "; === GPU kernel: resident byte feedback phase sets ===",
        "define void @vl_apply_feedback_sets_gpu(ptr %storage_base, ptr %phases, ptr %states, ptr %offsets, ptr %values, i32 %set_count, i32 %current_phase, i64 %storage_stride, i32 %nstates) {",
        "entry:",
        "  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()",
        "  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()",
        "  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()",
        "  %gid_mul = mul i32 %bid, %bdim",
        "  %gid32   = add i32 %gid_mul, %tid",
        "  %total = mul i32 %set_count, %nstates",
        "  %in_range = icmp ult i32 %gid32, %total",
        "  br i1 %in_range, label %body, label %exit",
        "",
        "body:",
        "  %set_idx = urem i32 %gid32, %set_count",
        "  %state_idx32 = udiv i32 %gid32, %set_count",
        "  %set_idx64 = zext i32 %set_idx to i64",
        "  %phase_ptr = getelementptr inbounds i32, ptr %phases, i64 %set_idx64",
        "  %phase = load i32, ptr %phase_ptr, align 4",
        "  %phase_match = icmp eq i32 %phase, %current_phase",
        "  br i1 %phase_match, label %state_filter, label %exit",
        "",
        "state_filter:",
        "  %state_ptr = getelementptr inbounds i32, ptr %states, i64 %set_idx64",
        "  %target_state = load i32, ptr %state_ptr, align 4",
        "  %all_states = icmp eq i32 %target_state, -1",
        "  %state_match = icmp eq i32 %target_state, %state_idx32",
        "  %state_ok = or i1 %all_states, %state_match",
        "  br i1 %state_ok, label %apply, label %exit",
        "",
        "apply:",
        "  %state_idx = zext i32 %state_idx32 to i64",
        "  %state_base = mul i64 %state_idx, %storage_stride",
        "  %offset_ptr = getelementptr inbounds i64, ptr %offsets, i64 %set_idx64",
        "  %local = load i64, ptr %offset_ptr, align 8",
        "  %value_ptr = getelementptr inbounds i8, ptr %values, i64 %set_idx64",
        "  %value = load i8, ptr %value_ptr, align 1",
        "  %off = add i64 %state_base, %local",
        "  %dst = getelementptr inbounds i8, ptr %storage_base, i64 %off",
        "  store i8 %value, ptr %dst, align 1",
        "  br label %exit",
        "",
        "exit:",
        "  ret void",
        "}",
        "",
    ]


def feedback_combined_kernel_lines() -> list[str]:
    return [
        "; === GPU kernel: combined resident feedback edges, increments, and phase sets ===",
        "define void @vl_apply_feedback_combined_gpu(ptr %storage_base, ptr %src_offsets, ptr %dst_offsets, i32 %edge_count, ptr %increment_offsets, ptr %increment_deltas, i32 %increment_count, ptr %set_phases, ptr %set_states, ptr %set_offsets, ptr %set_values, i32 %set_count, i32 %current_phase, i64 %storage_stride, i32 %nstates) {",
        "entry:",
        "  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()",
        "  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()",
        "  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()",
        "  %gid_mul = mul i32 %bid, %bdim",
        "  %gid32   = add i32 %gid_mul, %tid",
        "  %edge_total = mul i32 %edge_count, %nstates",
        "  %increment_total = mul i32 %increment_count, %nstates",
        "  %set_total = mul i32 %set_count, %nstates",
        "  %edge_increment_total = add i32 %edge_total, %increment_total",
        "  %total = add i32 %edge_increment_total, %set_total",
        "  %in_range = icmp ult i32 %gid32, %total",
        "  br i1 %in_range, label %dispatch, label %exit",
        "",
        "dispatch:",
        "  %is_edge = icmp ult i32 %gid32, %edge_total",
        "  br i1 %is_edge, label %edge_body, label %after_edge",
        "",
        "after_edge:",
        "  %is_increment = icmp ult i32 %gid32, %edge_increment_total",
        "  br i1 %is_increment, label %increment_body, label %set_body",
        "",
        "edge_body:",
        "  %edge_idx = urem i32 %gid32, %edge_count",
        "  %edge_state_idx32 = udiv i32 %gid32, %edge_count",
        "  %edge_idx64 = zext i32 %edge_idx to i64",
        "  %edge_state_idx = zext i32 %edge_state_idx32 to i64",
        "  %edge_state_base = mul i64 %edge_state_idx, %storage_stride",
        "  %src_offset_ptr = getelementptr inbounds i64, ptr %src_offsets, i64 %edge_idx64",
        "  %src_local = load i64, ptr %src_offset_ptr, align 8",
        "  %dst_offset_ptr = getelementptr inbounds i64, ptr %dst_offsets, i64 %edge_idx64",
        "  %dst_local = load i64, ptr %dst_offset_ptr, align 8",
        "  %src_off = add i64 %edge_state_base, %src_local",
        "  %dst_off = add i64 %edge_state_base, %dst_local",
        "  %src = getelementptr inbounds i8, ptr %storage_base, i64 %src_off",
        "  %edge_value = load i8, ptr %src, align 1",
        "  %edge_dst = getelementptr inbounds i8, ptr %storage_base, i64 %dst_off",
        "  store i8 %edge_value, ptr %edge_dst, align 1",
        "  br label %exit",
        "",
        "increment_body:",
        "  %increment_gid = sub i32 %gid32, %edge_total",
        "  %increment_idx = urem i32 %increment_gid, %increment_count",
        "  %increment_state_idx32 = udiv i32 %increment_gid, %increment_count",
        "  %increment_idx64 = zext i32 %increment_idx to i64",
        "  %increment_state_idx = zext i32 %increment_state_idx32 to i64",
        "  %increment_state_base = mul i64 %increment_state_idx, %storage_stride",
        "  %increment_offset_ptr = getelementptr inbounds i64, ptr %increment_offsets, i64 %increment_idx64",
        "  %increment_local = load i64, ptr %increment_offset_ptr, align 8",
        "  %increment_delta_ptr = getelementptr inbounds i8, ptr %increment_deltas, i64 %increment_idx64",
        "  %increment_delta = load i8, ptr %increment_delta_ptr, align 1",
        "  %increment_off = add i64 %increment_state_base, %increment_local",
        "  %increment_dst = getelementptr inbounds i8, ptr %storage_base, i64 %increment_off",
        "  %increment_old = load i8, ptr %increment_dst, align 1",
        "  %increment_new = add i8 %increment_old, %increment_delta",
        "  store i8 %increment_new, ptr %increment_dst, align 1",
        "  br label %exit",
        "",
        "set_body:",
        "  %set_gid = sub i32 %gid32, %edge_increment_total",
        "  %set_idx = urem i32 %set_gid, %set_count",
        "  %set_state_idx32 = udiv i32 %set_gid, %set_count",
        "  %set_idx64 = zext i32 %set_idx to i64",
        "  %phase_ptr = getelementptr inbounds i32, ptr %set_phases, i64 %set_idx64",
        "  %phase = load i32, ptr %phase_ptr, align 4",
        "  %phase_match = icmp eq i32 %phase, %current_phase",
        "  br i1 %phase_match, label %set_state_filter, label %exit",
        "",
        "set_state_filter:",
        "  %set_state_ptr = getelementptr inbounds i32, ptr %set_states, i64 %set_idx64",
        "  %set_target_state = load i32, ptr %set_state_ptr, align 4",
        "  %set_all_states = icmp eq i32 %set_target_state, -1",
        "  %set_state_match = icmp eq i32 %set_target_state, %set_state_idx32",
        "  %set_state_ok = or i1 %set_all_states, %set_state_match",
        "  br i1 %set_state_ok, label %set_apply, label %exit",
        "",
        "set_apply:",
        "  %set_state_idx = zext i32 %set_state_idx32 to i64",
        "  %set_state_base = mul i64 %set_state_idx, %storage_stride",
        "  %set_offset_ptr = getelementptr inbounds i64, ptr %set_offsets, i64 %set_idx64",
        "  %set_local = load i64, ptr %set_offset_ptr, align 8",
        "  %set_value_ptr = getelementptr inbounds i8, ptr %set_values, i64 %set_idx64",
        "  %set_value = load i8, ptr %set_value_ptr, align 1",
        "  %set_off = add i64 %set_state_base, %set_local",
        "  %set_dst = getelementptr inbounds i8, ptr %storage_base, i64 %set_off",
        "  store i8 %set_value, ptr %set_dst, align 1",
        "  br label %exit",
        "",
        "exit:",
        "  ret void",
        "}",
        "",
    ]


def metadata_lines(text: str) -> list[str]:
    lines: list[str] = []
    max_id = -1
    for line in text.splitlines():
        if re.match(r"^!\d+\s*=", line):
            mid = int(re.match(r"^!(\d+)", line).group(1))
            max_id = max(max_id, mid)
            lines.append(line)
    lines.append("")
    kernel_id = max_id + 1
    patch_kernel_id = kernel_id + 1
    init_replication_kernel_id = kernel_id + 2
    feedback_kernel_id = kernel_id + 3
    feedback_increment_kernel_id = kernel_id + 4
    feedback_set_kernel_id = kernel_id + 5
    feedback_combined_kernel_id = kernel_id + 6
    lines.append(f'!{kernel_id} = !{{ptr @vl_eval_batch_gpu, !"kernel", i32 1}}')
    lines.append(f'!{patch_kernel_id} = !{{ptr @vl_apply_patch_schedule_gpu, !"kernel", i32 1}}')
    lines.append(f'!{init_replication_kernel_id} = !{{ptr @vl_replicate_init_state_gpu, !"kernel", i32 1}}')
    lines.append(f'!{feedback_kernel_id} = !{{ptr @vl_apply_feedback_edges_gpu, !"kernel", i32 1}}')
    lines.append(f'!{feedback_increment_kernel_id} = !{{ptr @vl_apply_feedback_increments_gpu, !"kernel", i32 1}}')
    lines.append(f'!{feedback_set_kernel_id} = !{{ptr @vl_apply_feedback_sets_gpu, !"kernel", i32 1}}')
    lines.append(f'!{feedback_combined_kernel_id} = !{{ptr @vl_apply_feedback_combined_gpu, !"kernel", i32 1}}')
    lines.append(
        f"!nvvm.annotations = !{{!{kernel_id}, !{patch_kernel_id}, !{init_replication_kernel_id}, !{feedback_kernel_id}, !{feedback_increment_kernel_id}, !{feedback_set_kernel_id}, !{feedback_combined_kernel_id}}}"
    )
    return lines
